version: '3.8'

services:

  webapi:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: composer-api
    environment:
      ASPNETCORE_ENVIRONMENT: ${ASPNETCORE_ENVIRONMENT}
      ASPNETCORE_HTTP_PORTS: 8080
      POSTGRES__HOST: db
      POSTGRES__PORT: 5432
      POSTGRES__DATABASE: composer_db
      POSTGRES__USERNAME: postgres
      POSTGRES__PASSWORD: StrongPassword123!
      JWT__ISSUER: https://api.com
      JWT__AUDIENCE: https://client.com
      JWT__SECRET_KEY: a-string-secret-at-least-256-bits-long
      JWT__EXPIRY_IN_MINUTES: 60
    ports:
      - "8080:8080"
    networks:
      - composer-net
    depends_on:
      db:
        condition: service_healthy
    restart: unless-stopped

  db:
    image: postgres:17
    container_name: composer-db
    environment:
      POSTGRES_DB: composer_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: StrongPassword123!
    ports:
      - "5432:5432"
    networks:
      - composer-net
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d composer_db"]
      interval: 5s
      timeout: 5s
      retries: 5
    restart: unless-stopped

networks:
  composer-net:
    driver: bridge