services:

  frontend:
    build:
      context: .
      dockerfile: frontend.Dockerfile
    container_name: composer-frontend
    ports:
      - "3000:3000"
    networks:
      - composer-net
    depends_on:
      - webapi
    restart: unless-stopped

  webapi:
    build:
      context: .
      dockerfile: backend.Dockerfile
    container_name: composer-webapi
    environment:
      ASPNETCORE_ENVIRONMENT: ${ASPNETCORE_ENVIRONMENT}
      ASPNETCORE_HTTP_PORTS: 8080
      POSTGRES__HOST: db
      POSTGRES__PORT: 5432
      POSTGRES__DATABASE: ${POSTGRES__DATABASE}
      POSTGRES__USERNAME: ${POSTGRES__USERNAME}
      POSTGRES__PASSWORD: ${POSTGRES__PASSWORD}
      JWT__ISSUER: ${JWT__ISSUER}
      JWT__AUDIENCE: ${JWT__AUDIENCE}
      JWT__SECRET_KEY: ${JWT__SECRET_KEY}
      JWT__EXPIRY_IN_MINUTES: ${JWT__EXPIRY_IN_MINUTES}
      TWITCH__CLIENT_ID: ${TWITCH__CLIENT_ID}
      TWITCH__CLIENT_SECRET: ${TWITCH__CLIENT_SECRET}
      TWITCH__REDIRECT_URI: ${TWITCH__REDIRECT_URI}
      ADMIN_BOOTSTRAP__COMPOSER__USERNAME: ${ADMIN_BOOTSTRAP__COMPOSER__USERNAME}
      ADMIN_BOOTSTRAP__COMPOSER__PASSWORD: ${ADMIN_BOOTSTRAP__COMPOSER__PASSWORD}
      ADMIN_BOOTSTRAP__MODERATOR__USERNAME: ${ADMIN_BOOTSTRAP__MODERATOR__USERNAME}
      ADMIN_BOOTSTRAP__MODERATOR__PASSWORD: ${ADMIN_BOOTSTRAP__MODERATOR__PASSWORD}
    ports:
      - "8080:8080"
    networks:
      - composer-net
    depends_on:
      db:
        condition: service_healthy
    restart: unless-stopped

  db:
    image: postgres:18
    container_name: composer-db
    environment:
      POSTGRES_DB: ${POSTGRES__DATABASE}
      POSTGRES_USER: ${POSTGRES__USERNAME}
      POSTGRES_PASSWORD: ${POSTGRES__PASSWORD}
    ports:
      - "5432:5432"
    networks:
      - composer-net
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES__USERNAME} -d ${POSTGRES__DATABASE}"]
      interval: 5s
      timeout: 5s
      retries: 5
    restart: unless-stopped

networks:
  composer-net:
    driver: bridge