/* tslint:disable */
/* eslint-disable */
/**
 * Faryma.Composer.Api - SignalR Hub
 * No description provided (generated by OpenAPI Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as signalR from "@microsoft/signalr";
// Import types from REST API
import type {Configuration, OrderPositionDto} from "@/api/rest";

/**
 * Тип обновления очереди
 */
export const OrderQueueUpdateType = {
    Unspecified: 0,
    OrderCreated: 1,
    OrderMovedUp: 2,
    TrackUrlAdded: 3,
    OrderTaken: 4,
    OrderCompleted: 5,
    OrderFrozen: 6,
    OrderUnfrozen: 7,
    OrderCanceled: 8,
    StreamStarted: 9,
    StreamCompleted: 10
} as const;

export type OrderQueueUpdateType = typeof OrderQueueUpdateType[keyof typeof OrderQueueUpdateType];

/**
 * Событие изменения очереди
 */
export interface OrderQueueUpdatedEvent {
    /**
     * Версия для синхронизации состояния очереди
     */
    'syncVersion'?: number;
    /**
     * Тип обновления очереди
     */
    'orderQueueUpdateType'?: OrderQueueUpdateType;
    /**
     * Позиции заказов
     */
    'orderPositions': Array<OrderPositionDto>;
}

/**
 * Сообщение о состоянии очереди
 */
export interface OrderQueueSnapshotMessage {
    /**
     * Версия для синхронизации состояния очереди
     */
    'syncVersion'?: number;
    /**
     * Активные заказы
     */
    'activeOrders': Array<OrderPositionDto>;
    /**
     * Заказ в работе
     */
    'inProgressOrder'?: OrderPositionDto | null;
    /**
     * Выполненные заказы
     */
    'completedOrders': Array<OrderPositionDto>;
    /**
     * Запланированные заказы
     */
    'scheduledOrders': Array<OrderPositionDto>;
    /**
     * Замороженные заказы
     */
    'frozenOrders': Array<OrderPositionDto>;
}

export interface OrderQueueNotificationHubCallbacks {
    /**
     * Передача полного снимка очереди
     * Отправляется при подключении клиента или по запросу
     */
    onReceiveSnapshot?: (message: OrderQueueSnapshotMessage) => void;

    /**
     * Инкрементальные обновления очереди
     * Отправляется при каждом изменении очереди
     */
    onReceiveUpdated?: (event: OrderQueueUpdatedEvent) => void;
}

export interface OrderQueueNotificationHubConfig {
    /**
     * Base URL для подключения
     */
    baseUrl?: string;

    /**
     * Конфигурация (для accessToken)
     */
    configuration?: Configuration;

    /**
     * Автоматическое переподключение
     */
    automaticReconnect?: boolean;

    /**
     * Дополнительные опции для SignalR HubConnectionBuilder
     */
    additionalOptions?: Partial<signalR.IHttpConnectionOptions>;
}

/**
 * OrderQueueNotificationHub - SignalR Hub Client
 * Очередь заказов
 */
export class OrderQueueNotificationHub {
    private connection: signalR.HubConnection;
    private callbacks: OrderQueueNotificationHubCallbacks = {};
    private basePath: string;
    private configuration?: Configuration;

    /**
     * Creates an instance of OrderQueueNotificationHub.
     * @param {OrderQueueNotificationHubConfig} [config={}]
     */
    constructor(config: OrderQueueNotificationHubConfig = {}) {
        this.basePath = config.baseUrl ?? "http://localhost";
        this.configuration = config.configuration;

        const hubUrl = `${this.basePath}/api/OrderQueueNotificationHub`;

        const builder = new signalR.HubConnectionBuilder()
            .withUrl(hubUrl, {
                ...config.additionalOptions,
                accessTokenFactory: async () => {
                    if (this.configuration?.accessToken) {
                        return typeof this.configuration.accessToken === 'function'
                            ? await this.configuration.accessToken()
                            : await this.configuration.accessToken;
                    }
                    return "";
                }
            });

        if (config.automaticReconnect !== false) {
            builder.withAutomaticReconnect();
        }

        this.connection = builder.build();

        // Register handlers
        this.connection.on("ReceiveSnapshot", (message: OrderQueueSnapshotMessage) => {
            if (this.callbacks.onReceiveSnapshot) {
                this.callbacks.onReceiveSnapshot(message);
            }
        });

        this.connection.on("ReceiveUpdated", (event: OrderQueueUpdatedEvent) => {
            if (this.callbacks.onReceiveUpdated) {
                this.callbacks.onReceiveUpdated(event);
            }
        });
    }

    /**
     * Устанавливает callback функции для обработки событий
     * @param {OrderQueueNotificationHubCallbacks} callbacks
     */
    public setCallbacks(callbacks: OrderQueueNotificationHubCallbacks): void {
        this.callbacks = { ...this.callbacks, ...callbacks };
    }

    /**
     * Запускает подключение к Hub
     * @returns {Promise<void>}
     */
    public async start(): Promise<void> {
        if (this.connection.state === signalR.HubConnectionState.Disconnected) {
            await this.connection.start();
        }
    }

    /**
     * Останавливает подключение к Hub
     * @returns {Promise<void>}
     */
    public async stop(): Promise<void> {
        if (this.connection.state !== signalR.HubConnectionState.Disconnected) {
            await this.connection.stop();
        }
    }

    /**
     * Запрос полного снимка очереди
     * Позволяет клиенту синхронизировать очередь по требованию
     * @returns {Promise<void>}
     */
    public async getSnapshot(): Promise<void> {
        await this.connection.invoke("GetSnapshot");
    }

    /**
     * Возвращает текущее состояние подключения
     * @returns {signalR.HubConnectionState}
     */
    public getConnectionState(): signalR.HubConnectionState {
        return this.connection.state;
    }

    /**
     * Подписка на событие reconnecting
     * @param {(error?: Error) => void} callback
     */
    public onReconnecting(callback: (error?: Error) => void): void {
        this.connection.onreconnecting(callback);
    }

    /**
     * Подписка на событие reconnected
     * @param {(connectionId?: string) => void} callback
     */
    public onReconnected(callback: (connectionId?: string) => void): void {
        this.connection.onreconnected(callback);
    }

    /**
     * Подписка на событие close
     * @param {(error?: Error) => void} callback
     */
    public onClose(callback: (error?: Error) => void): void {
        this.connection.onclose(callback);
    }
}

/**
 * OrderQueueNotificationHubApi - functional programming interface
 */
export const OrderQueueNotificationHubApiFp = function(config?: OrderQueueNotificationHubConfig) {
    const hub = new OrderQueueNotificationHub(config);

    return {
        /**
         * Запускает подключение к Hub
         */
        start: async () => {
            await hub.start();
            return hub;
        },

        /**
         * Останавливает подключение к Hub
         */
        stop: async () => {
            await hub.stop();
        },

        /**
         * Запрос полного снимка очереди
         */
        getSnapshot: async () => {
            await hub.getSnapshot();
        },

        /**
         * Устанавливает callback для ReceiveSnapshot
         */
        onReceiveSnapshot: (callback: (message: OrderQueueSnapshotMessage) => void) => {
            hub.setCallbacks({ onReceiveSnapshot: callback });
            return hub;
        },

        /**
         * Устанавливает callback для ReceiveUpdated
         */
        onReceiveUpdated: (callback: (event: OrderQueueUpdatedEvent) => void) => {
            hub.setCallbacks({ onReceiveUpdated: callback });
            return hub;
        },

        /**
         * Возвращает экземпляр Hub
         */
        getHub: () => hub
    };
};

/**
 * OrderQueueNotificationHubApi - object-oriented interface
 */
export class OrderQueueNotificationHubApi extends OrderQueueNotificationHub {
    constructor(config?: OrderQueueNotificationHubConfig) {
        super(config);
    }
}