// <auto-generated />
using System;
using System.Collections.Generic;
using Faryma.Composer.Contracts.Infrastructure.Enums;
using Faryma.Composer.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Faryma.Composer.MigrationsBundle.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260110060730_Init")]
    partial class Init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("app")
                .HasAnnotation("ProductVersion", "10.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "app", "account_top_up_provider", new[] { "unspecified", "donationalerts", "donatty", "twitch_channel_points", "manual" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "app", "composer_stream_status", new[] { "unspecified", "planned", "live", "completed", "canceled" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "app", "composer_stream_type", new[] { "unspecified", "donation", "debt", "charity" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "app", "order_category_type", new[] { "unspecified", "out_of_queue", "donation", "debt" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "app", "review_order_status", new[] { "unspecified", "preorder", "pending", "in_progress", "completed", "canceled" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "app", "review_order_type", new[] { "unspecified", "out_of_queue", "donation", "free", "charity", "custom" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "app", "transaction_kind", new[] { "unspecified", "account_top_up", "payment", "reversal" });
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Faryma.Composer.Contracts.Infrastructure.Entities.AppSettingsEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<int>("ReviewOrderNominalAmount")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("app_settings", "app");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            ReviewOrderNominalAmount = 750
                        });
                });

            modelBuilder.Entity("Faryma.Composer.Contracts.Infrastructure.Entities.ComposerStreamEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateOnly>("EventDate")
                        .HasColumnType("date");

                    b.Property<DateTime?>("StartedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<ComposerStreamStatus>("Status")
                        .HasColumnType("app.composer_stream_status");

                    b.Property<ComposerStreamType>("Type")
                        .HasColumnType("app.composer_stream_type");

                    b.HasKey("Id");

                    b.HasIndex("EventDate")
                        .IsUnique();

                    b.ToTable("composer_streams", "app");
                });

            modelBuilder.Entity("Faryma.Composer.Contracts.Infrastructure.Entities.ReviewEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("RatingValue")
                        .HasColumnType("integer");

                    b.Property<long?>("ReviewOrderId")
                        .HasColumnType("bigint");

                    b.Property<long?>("TrackId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("ReviewOrderId")
                        .IsUnique();

                    b.HasIndex("TrackId");

                    b.ToTable("reviews", "app");
                });

            modelBuilder.Entity("Faryma.Composer.Contracts.Infrastructure.Entities.TrackArtistEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("NormalizedName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique();

                    b.ToTable("track_artists", "app");
                });

            modelBuilder.Entity("Faryma.Composer.Contracts.Infrastructure.Entities.TrackCountryEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("track_countries", "app");
                });

            modelBuilder.Entity("Faryma.Composer.Contracts.Infrastructure.Entities.TrackEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("AddedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("AddedByUserNicknameId")
                        .HasColumnType("uuid");

                    b.Property<long?>("CountryId")
                        .HasColumnType("bigint");

                    b.Property<string>("CoverUrl")
                        .HasColumnType("text");

                    b.PrimitiveCollection<List<string>>("ExtendedGenres")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.Property<DateOnly?>("ReleaseDate")
                        .HasColumnType("date");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("AddedByUserNicknameId");

                    b.HasIndex("CountryId");

                    b.ToTable("tracks", "app");
                });

            modelBuilder.Entity("Faryma.Composer.Contracts.Infrastructure.Entities.TrackGenreEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("track_genres", "app");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            Name = "электронное"
                        },
                        new
                        {
                            Id = 2L,
                            Name = "фолк"
                        },
                        new
                        {
                            Id = 3L,
                            Name = "рок"
                        },
                        new
                        {
                            Id = 4L,
                            Name = "разное"
                        },
                        new
                        {
                            Id = 5L,
                            Name = "джаз"
                        },
                        new
                        {
                            Id = 6L,
                            Name = "метал"
                        },
                        new
                        {
                            Id = 7L,
                            Name = "рэп"
                        },
                        new
                        {
                            Id = 8L,
                            Name = "поп"
                        },
                        new
                        {
                            Id = 9L,
                            Name = "оркестровый"
                        },
                        new
                        {
                            Id = 10L,
                            Name = "фанк"
                        },
                        new
                        {
                            Id = 11L,
                            Name = "мюзикл/опера"
                        },
                        new
                        {
                            Id = 12L,
                            Name = "инди"
                        },
                        new
                        {
                            Id = 13L,
                            Name = "поп-рок"
                        },
                        new
                        {
                            Id = 14L,
                            Name = "шансон"
                        },
                        new
                        {
                            Id = 15L,
                            Name = "специфическое"
                        },
                        new
                        {
                            Id = 16L,
                            Name = "баллада"
                        },
                        new
                        {
                            Id = 17L,
                            Name = "фортепиано"
                        },
                        new
                        {
                            Id = 18L,
                            Name = "инструментал"
                        });
                });

            modelBuilder.Entity("Faryma.Composer.Contracts.Infrastructure.Entities.TransactionEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("Credit")
                        .HasColumnType("bigint");

                    b.Property<long>("Debit")
                        .HasColumnType("bigint");

                    b.Property<TransactionKind>("Kind")
                        .HasColumnType("app.transaction_kind");

                    b.Property<long>("SourceId")
                        .HasColumnType("bigint");

                    b.Property<Guid>("UserAccountId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("SourceId");

                    b.HasIndex("UserAccountId");

                    b.ToTable("transactions", "app");
                });

            modelBuilder.Entity("Faryma.Composer.Contracts.Infrastructure.Entities.TransactionSources.TransactionSourceEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("transaction_sources", "app");

                    b.UseTptMappingStrategy();
                });

            modelBuilder.Entity("Faryma.Composer.Contracts.Infrastructure.Entities.UserAccountEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<long>("Balance")
                        .HasColumnType("bigint");

                    b.Property<Guid>("UserNicknameId")
                        .HasColumnType("uuid");

                    b.Property<uint>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id");

                    b.HasIndex("UserNicknameId")
                        .IsUnique();

                    b.ToTable("user_accounts", "app");
                });

            modelBuilder.Entity("Faryma.Composer.Contracts.Infrastructure.Entities.UserEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("integer");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("boolean");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("text");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers", "app");
                });

            modelBuilder.Entity("Faryma.Composer.Contracts.Infrastructure.Entities.UserNicknameEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Nickname")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("NormalizedNickname")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedNickname")
                        .IsUnique();

                    b.HasIndex("UserId");

                    b.ToTable("user_nicknames", "app");
                });

            modelBuilder.Entity("Faryma.Composer.Contracts.Infrastructure.Entities.UserTrackRatingEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Comment")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("RatingValue")
                        .HasColumnType("integer");

                    b.Property<long>("TrackId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("TrackId");

                    b.HasIndex("UserId");

                    b.ToTable("user_track_ratings", "app");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.DataProtection.EntityFrameworkCore.DataProtectionKey", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("FriendlyName")
                        .HasColumnType("text");

                    b.Property<string>("Xml")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("DataProtectionKeys", "app");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", "app");

                    b.HasData(
                        new
                        {
                            Id = new Guid("9c3ddcde-24e7-458c-8d9c-1e5f424d3ddd"),
                            ConcurrencyStamp = "9C3DDCDE-24E7-458C-8D9C-1E5F424D3DDD",
                            Name = "Composer",
                            NormalizedName = "COMPOSER"
                        },
                        new
                        {
                            Id = new Guid("ac0b9e85-a06f-4655-822b-9c125d8d7bb4"),
                            ConcurrencyStamp = "AC0B9E85-A06F-4655-822B-9C125D8D7BB4",
                            Name = "Moderator",
                            NormalizedName = "MODERATOR"
                        },
                        new
                        {
                            Id = new Guid("910c6755-4833-4c62-8df7-4241a159a8d2"),
                            ConcurrencyStamp = "910C6755-4833-4C62-8DF7-4241A159A8D2",
                            Name = "User",
                            NormalizedName = "USER"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", "app");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", "app");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("text");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("text");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", "app");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", "app");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("Value")
                        .HasColumnType("text");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", "app");
                });

            modelBuilder.Entity("ReviewOrderEntityUserNicknameEntity", b =>
                {
                    b.Property<long>("ReviewOrdersId")
                        .HasColumnType("bigint");

                    b.Property<Guid>("UserNicknamesId")
                        .HasColumnType("uuid");

                    b.HasKey("ReviewOrdersId", "UserNicknamesId");

                    b.HasIndex("UserNicknamesId");

                    b.ToTable("ReviewOrderEntityUserNicknameEntity", "app");
                });

            modelBuilder.Entity("TrackArtistEntityTrackEntity", b =>
                {
                    b.Property<long>("ArtistsId")
                        .HasColumnType("bigint");

                    b.Property<long>("TracksId")
                        .HasColumnType("bigint");

                    b.HasKey("ArtistsId", "TracksId");

                    b.HasIndex("TracksId");

                    b.ToTable("TrackArtistEntityTrackEntity", "app");
                });

            modelBuilder.Entity("TrackArtistEntityUserEntity", b =>
                {
                    b.Property<long>("AssociatedArtistsId")
                        .HasColumnType("bigint");

                    b.Property<Guid>("UsersId")
                        .HasColumnType("uuid");

                    b.HasKey("AssociatedArtistsId", "UsersId");

                    b.HasIndex("UsersId");

                    b.ToTable("TrackArtistEntityUserEntity", "app");
                });

            modelBuilder.Entity("TrackEntityTrackGenreEntity", b =>
                {
                    b.Property<long>("GenresId")
                        .HasColumnType("bigint");

                    b.Property<long>("TracksId")
                        .HasColumnType("bigint");

                    b.HasKey("GenresId", "TracksId");

                    b.HasIndex("TracksId");

                    b.ToTable("TrackEntityTrackGenreEntity", "app");
                });

            modelBuilder.Entity("Faryma.Composer.Contracts.Infrastructure.Entities.TransactionSources.AccountTopUpEntity", b =>
                {
                    b.HasBaseType("Faryma.Composer.Contracts.Infrastructure.Entities.TransactionSources.TransactionSourceEntity");

                    b.Property<AccountTopUpProvider>("Provider")
                        .HasColumnType("app.account_top_up_provider");

                    b.Property<Guid>("UserAccountId")
                        .HasColumnType("uuid");

                    b.HasIndex("UserAccountId");

                    b.ToTable("account_top_ups", "app");
                });

            modelBuilder.Entity("Faryma.Composer.Contracts.Infrastructure.Entities.TransactionSources.ReviewOrderEntity", b =>
                {
                    b.HasBaseType("Faryma.Composer.Contracts.Infrastructure.Entities.TransactionSources.TransactionSourceEntity");

                    b.Property<OrderCategoryType>("CategoryType")
                        .HasColumnType("app.order_category_type");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("CreationStreamId")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("InProgressAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsFrozen")
                        .HasColumnType("boolean");

                    b.Property<string>("MainNickname")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("MainNormalizedNickname")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long>("NominalAmount")
                        .HasColumnType("bigint");

                    b.Property<long>("PayableAmount")
                        .HasColumnType("bigint");

                    b.Property<long?>("ProcessingStreamId")
                        .HasColumnType("bigint");

                    b.Property<ReviewOrderStatus>("Status")
                        .HasColumnType("app.review_order_status");

                    b.Property<long?>("TrackId")
                        .HasColumnType("bigint");

                    b.Property<string>("TrackUrl")
                        .HasColumnType("text");

                    b.Property<ReviewOrderType>("Type")
                        .HasColumnType("app.review_order_type");

                    b.Property<string>("UserComment")
                        .HasColumnType("text");

                    b.HasIndex("CreationStreamId");

                    b.HasIndex("ProcessingStreamId");

                    b.HasIndex("TrackId");

                    b.ToTable("review_orders", "app");
                });

            modelBuilder.Entity("Faryma.Composer.Contracts.Infrastructure.Entities.TransactionSources.TransactionReversalEntity", b =>
                {
                    b.HasBaseType("Faryma.Composer.Contracts.Infrastructure.Entities.TransactionSources.TransactionSourceEntity");

                    b.Property<string>("Reason")
                        .HasColumnType("text");

                    b.Property<long?>("ReversalTransactionId")
                        .HasColumnType("bigint");

                    b.Property<Guid>("ReversedByUserId")
                        .HasColumnType("uuid");

                    b.Property<long>("ReversedTransactionId")
                        .HasColumnType("bigint");

                    b.HasIndex("ReversalTransactionId")
                        .IsUnique();

                    b.HasIndex("ReversedByUserId");

                    b.HasIndex("ReversedTransactionId")
                        .IsUnique();

                    b.ToTable("transaction_reversals", "app");
                });

            modelBuilder.Entity("Faryma.Composer.Contracts.Infrastructure.Entities.ReviewEntity", b =>
                {
                    b.HasOne("Faryma.Composer.Contracts.Infrastructure.Entities.TransactionSources.ReviewOrderEntity", "ReviewOrder")
                        .WithOne("Review")
                        .HasForeignKey("Faryma.Composer.Contracts.Infrastructure.Entities.ReviewEntity", "ReviewOrderId");

                    b.HasOne("Faryma.Composer.Contracts.Infrastructure.Entities.TrackEntity", "Track")
                        .WithMany("Reviews")
                        .HasForeignKey("TrackId");

                    b.Navigation("ReviewOrder");

                    b.Navigation("Track");
                });

            modelBuilder.Entity("Faryma.Composer.Contracts.Infrastructure.Entities.TrackEntity", b =>
                {
                    b.HasOne("Faryma.Composer.Contracts.Infrastructure.Entities.UserNicknameEntity", "AddedBy")
                        .WithMany("UploadedTracks")
                        .HasForeignKey("AddedByUserNicknameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Faryma.Composer.Contracts.Infrastructure.Entities.TrackCountryEntity", "Country")
                        .WithMany("Tracks")
                        .HasForeignKey("CountryId");

                    b.OwnsMany("Faryma.Composer.Contracts.Infrastructure.Models.TrackTag", "Tags", b1 =>
                        {
                            b1.Property<long>("TrackEntityId");

                            b1.Property<int>("__synthesizedOrdinal")
                                .ValueGeneratedOnAdd();

                            b1.Property<string>("Meta");

                            b1.Property<string>("Name")
                                .IsRequired();

                            b1.HasKey("TrackEntityId", "__synthesizedOrdinal");

                            b1.ToTable("tracks", "app");

                            b1.ToJson("Tags");

                            b1.WithOwner()
                                .HasForeignKey("TrackEntityId");
                        });

                    b.Navigation("AddedBy");

                    b.Navigation("Country");

                    b.Navigation("Tags");
                });

            modelBuilder.Entity("Faryma.Composer.Contracts.Infrastructure.Entities.TransactionEntity", b =>
                {
                    b.HasOne("Faryma.Composer.Contracts.Infrastructure.Entities.TransactionSources.TransactionSourceEntity", "Source")
                        .WithMany("Transactions")
                        .HasForeignKey("SourceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Faryma.Composer.Contracts.Infrastructure.Entities.UserAccountEntity", "Account")
                        .WithMany("Transactions")
                        .HasForeignKey("UserAccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Account");

                    b.Navigation("Source");
                });

            modelBuilder.Entity("Faryma.Composer.Contracts.Infrastructure.Entities.UserAccountEntity", b =>
                {
                    b.HasOne("Faryma.Composer.Contracts.Infrastructure.Entities.UserNicknameEntity", "UserNickname")
                        .WithOne("Account")
                        .HasForeignKey("Faryma.Composer.Contracts.Infrastructure.Entities.UserAccountEntity", "UserNicknameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("UserNickname");
                });

            modelBuilder.Entity("Faryma.Composer.Contracts.Infrastructure.Entities.UserNicknameEntity", b =>
                {
                    b.HasOne("Faryma.Composer.Contracts.Infrastructure.Entities.UserEntity", "User")
                        .WithMany("UserNicknames")
                        .HasForeignKey("UserId");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Faryma.Composer.Contracts.Infrastructure.Entities.UserTrackRatingEntity", b =>
                {
                    b.HasOne("Faryma.Composer.Contracts.Infrastructure.Entities.TrackEntity", "Track")
                        .WithMany("UserRatings")
                        .HasForeignKey("TrackId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Faryma.Composer.Contracts.Infrastructure.Entities.UserEntity", "User")
                        .WithMany("TrackRatings")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Track");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.HasOne("Faryma.Composer.Contracts.Infrastructure.Entities.UserEntity", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.HasOne("Faryma.Composer.Contracts.Infrastructure.Entities.UserEntity", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Faryma.Composer.Contracts.Infrastructure.Entities.UserEntity", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.HasOne("Faryma.Composer.Contracts.Infrastructure.Entities.UserEntity", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ReviewOrderEntityUserNicknameEntity", b =>
                {
                    b.HasOne("Faryma.Composer.Contracts.Infrastructure.Entities.TransactionSources.ReviewOrderEntity", null)
                        .WithMany()
                        .HasForeignKey("ReviewOrdersId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Faryma.Composer.Contracts.Infrastructure.Entities.UserNicknameEntity", null)
                        .WithMany()
                        .HasForeignKey("UserNicknamesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("TrackArtistEntityTrackEntity", b =>
                {
                    b.HasOne("Faryma.Composer.Contracts.Infrastructure.Entities.TrackArtistEntity", null)
                        .WithMany()
                        .HasForeignKey("ArtistsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Faryma.Composer.Contracts.Infrastructure.Entities.TrackEntity", null)
                        .WithMany()
                        .HasForeignKey("TracksId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("TrackArtistEntityUserEntity", b =>
                {
                    b.HasOne("Faryma.Composer.Contracts.Infrastructure.Entities.TrackArtistEntity", null)
                        .WithMany()
                        .HasForeignKey("AssociatedArtistsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Faryma.Composer.Contracts.Infrastructure.Entities.UserEntity", null)
                        .WithMany()
                        .HasForeignKey("UsersId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("TrackEntityTrackGenreEntity", b =>
                {
                    b.HasOne("Faryma.Composer.Contracts.Infrastructure.Entities.TrackGenreEntity", null)
                        .WithMany()
                        .HasForeignKey("GenresId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Faryma.Composer.Contracts.Infrastructure.Entities.TrackEntity", null)
                        .WithMany()
                        .HasForeignKey("TracksId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Faryma.Composer.Contracts.Infrastructure.Entities.TransactionSources.AccountTopUpEntity", b =>
                {
                    b.HasOne("Faryma.Composer.Contracts.Infrastructure.Entities.TransactionSources.TransactionSourceEntity", null)
                        .WithOne()
                        .HasForeignKey("Faryma.Composer.Contracts.Infrastructure.Entities.TransactionSources.AccountTopUpEntity", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Faryma.Composer.Contracts.Infrastructure.Entities.UserAccountEntity", "Account")
                        .WithMany()
                        .HasForeignKey("UserAccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Account");
                });

            modelBuilder.Entity("Faryma.Composer.Contracts.Infrastructure.Entities.TransactionSources.ReviewOrderEntity", b =>
                {
                    b.HasOne("Faryma.Composer.Contracts.Infrastructure.Entities.ComposerStreamEntity", "CreationStream")
                        .WithMany("CreatedReviewOrders")
                        .HasForeignKey("CreationStreamId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Faryma.Composer.Contracts.Infrastructure.Entities.TransactionSources.TransactionSourceEntity", null)
                        .WithOne()
                        .HasForeignKey("Faryma.Composer.Contracts.Infrastructure.Entities.TransactionSources.ReviewOrderEntity", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Faryma.Composer.Contracts.Infrastructure.Entities.ComposerStreamEntity", "ProcessingStream")
                        .WithMany("ProcessedReviewOrders")
                        .HasForeignKey("ProcessingStreamId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Faryma.Composer.Contracts.Infrastructure.Entities.TrackEntity", "Track")
                        .WithMany("ReviewOrders")
                        .HasForeignKey("TrackId");

                    b.Navigation("CreationStream");

                    b.Navigation("ProcessingStream");

                    b.Navigation("Track");
                });

            modelBuilder.Entity("Faryma.Composer.Contracts.Infrastructure.Entities.TransactionSources.TransactionReversalEntity", b =>
                {
                    b.HasOne("Faryma.Composer.Contracts.Infrastructure.Entities.TransactionSources.TransactionSourceEntity", null)
                        .WithOne()
                        .HasForeignKey("Faryma.Composer.Contracts.Infrastructure.Entities.TransactionSources.TransactionReversalEntity", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Faryma.Composer.Contracts.Infrastructure.Entities.TransactionEntity", "ReversalTransaction")
                        .WithMany()
                        .HasForeignKey("ReversalTransactionId");

                    b.HasOne("Faryma.Composer.Contracts.Infrastructure.Entities.UserEntity", "ReversedByUser")
                        .WithMany()
                        .HasForeignKey("ReversedByUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Faryma.Composer.Contracts.Infrastructure.Entities.TransactionEntity", "ReversedTransaction")
                        .WithMany()
                        .HasForeignKey("ReversedTransactionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ReversalTransaction");

                    b.Navigation("ReversedByUser");

                    b.Navigation("ReversedTransaction");
                });

            modelBuilder.Entity("Faryma.Composer.Contracts.Infrastructure.Entities.ComposerStreamEntity", b =>
                {
                    b.Navigation("CreatedReviewOrders");

                    b.Navigation("ProcessedReviewOrders");
                });

            modelBuilder.Entity("Faryma.Composer.Contracts.Infrastructure.Entities.TrackCountryEntity", b =>
                {
                    b.Navigation("Tracks");
                });

            modelBuilder.Entity("Faryma.Composer.Contracts.Infrastructure.Entities.TrackEntity", b =>
                {
                    b.Navigation("ReviewOrders");

                    b.Navigation("Reviews");

                    b.Navigation("UserRatings");
                });

            modelBuilder.Entity("Faryma.Composer.Contracts.Infrastructure.Entities.TransactionSources.TransactionSourceEntity", b =>
                {
                    b.Navigation("Transactions");
                });

            modelBuilder.Entity("Faryma.Composer.Contracts.Infrastructure.Entities.UserAccountEntity", b =>
                {
                    b.Navigation("Transactions");
                });

            modelBuilder.Entity("Faryma.Composer.Contracts.Infrastructure.Entities.UserEntity", b =>
                {
                    b.Navigation("TrackRatings");

                    b.Navigation("UserNicknames");
                });

            modelBuilder.Entity("Faryma.Composer.Contracts.Infrastructure.Entities.UserNicknameEntity", b =>
                {
                    b.Navigation("Account")
                        .IsRequired();

                    b.Navigation("UploadedTracks");
                });

            modelBuilder.Entity("Faryma.Composer.Contracts.Infrastructure.Entities.TransactionSources.ReviewOrderEntity", b =>
                {
                    b.Navigation("Review");
                });
#pragma warning restore 612, 618
        }
    }
}
