// <auto-generated />
using System;
using System.Collections.Generic;
using Faryma.Composer.Contracts.Infrastructure.Enums;
using Faryma.Composer.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Faryma.Composer.MigrationsBundle.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("app")
                .HasAnnotation("ProductVersion", "10.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "app", "AccountTopUpProvider", new[] { "unspecified", "donationalerts", "donatty", "twitch_channel_points", "manual" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "app", "ComposerStreamStatus", new[] { "unspecified", "planned", "live", "completed", "canceled" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "app", "ComposerStreamType", new[] { "unspecified", "donation", "debt", "charity" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "app", "QueueCategory", new[] { "unspecified", "out_of_queue", "donation", "debt" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "app", "ReviewOrderStatus", new[] { "unspecified", "preorder", "awaiting_payment", "pending", "in_progress", "completed", "canceled" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "app", "ReviewOrderType", new[] { "unspecified", "out_of_queue", "donation", "free", "charity", "custom" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "app", "TransactionKind", new[] { "unspecified", "account_top_up", "payment", "reversal" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "app", "UserEntitlementKind", new[] { "unspecified", "amount_coupon", "service_token" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "app", "UserEntitlementTarget", new[] { "unspecified", "review_order", "out_of_queue_review_order", "detailed_review" });
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Faryma.Composer.Contracts.Infrastructure.Entities.AppSettingsEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("ReviewOrderDetailedReviewAmount")
                        .HasColumnType("bigint");

                    b.Property<long>("ReviewOrderExtraTimeAmountPerSecond")
                        .HasColumnType("bigint");

                    b.Property<long>("ReviewOrderNominalAmount")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.ToTable("app_settings", "app");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            ReviewOrderDetailedReviewAmount = 1000L,
                            ReviewOrderExtraTimeAmountPerSecond = 3L,
                            ReviewOrderNominalAmount = 1000L
                        });
                });

            modelBuilder.Entity("Faryma.Composer.Contracts.Infrastructure.Entities.ComposerStreamEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("CreatedByUserId")
                        .HasColumnType("uuid");

                    b.Property<DateOnly>("EventDate")
                        .HasColumnType("date");

                    b.Property<DateTime?>("StartedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<ComposerStreamStatus>("Status")
                        .HasColumnType("app.ComposerStreamStatus");

                    b.Property<ComposerStreamType>("Type")
                        .HasColumnType("app.ComposerStreamType");

                    b.HasKey("Id");

                    b.HasIndex("CreatedByUserId");

                    b.HasIndex("EventDate")
                        .IsUnique();

                    b.ToTable("composer_streams", "app");
                });

            modelBuilder.Entity("Faryma.Composer.Contracts.Infrastructure.Entities.IdempotencyRecordEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("EndpointKey")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("IdempotencyKey")
                        .HasColumnType("uuid");

                    b.Property<string>("RequestHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("ResponseJson")
                        .HasColumnType("jsonb");

                    b.Property<int?>("StatusCode")
                        .HasColumnType("integer");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ExpiresAt");

                    b.HasIndex("EndpointKey", "UserId", "IdempotencyKey")
                        .IsUnique();

                    b.ToTable("idempotency_records", "app");
                });

            modelBuilder.Entity("Faryma.Composer.Contracts.Infrastructure.Entities.RefreshTokenEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("FamilyId")
                        .HasColumnType("uuid");

                    b.Property<string>("ReplacedByTokenHash")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<DateTime?>("RevokedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<uint>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id");

                    b.HasIndex("FamilyId");

                    b.HasIndex("TokenHash")
                        .IsUnique();

                    b.HasIndex("UserId");

                    b.ToTable("refresh_tokens", "app");
                });

            modelBuilder.Entity("Faryma.Composer.Contracts.Infrastructure.Entities.ReviewEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("CreatedByUserId")
                        .HasColumnType("uuid");

                    b.Property<int>("RatingValue")
                        .HasColumnType("integer");

                    b.Property<long?>("ReviewOrderId")
                        .HasColumnType("bigint");

                    b.Property<string>("TimestampUrl")
                        .HasColumnType("text");

                    b.Property<long?>("TrackId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("CreatedByUserId");

                    b.HasIndex("ReviewOrderId")
                        .IsUnique();

                    b.HasIndex("TrackId");

                    b.ToTable("reviews", "app");
                });

            modelBuilder.Entity("Faryma.Composer.Contracts.Infrastructure.Entities.TrackArtistEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("NormalizedName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique();

                    b.ToTable("track_artists", "app");
                });

            modelBuilder.Entity("Faryma.Composer.Contracts.Infrastructure.Entities.TrackCountryEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("track_countries", "app");
                });

            modelBuilder.Entity("Faryma.Composer.Contracts.Infrastructure.Entities.TrackEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("AddedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("AddedByUserNicknameId")
                        .HasColumnType("uuid");

                    b.Property<long?>("CountryId")
                        .HasColumnType("bigint");

                    b.Property<string>("CoverUrl")
                        .HasColumnType("text");

                    b.Property<Guid>("CreatedByUserId")
                        .HasColumnType("uuid");

                    b.Property<int>("DurationSeconds")
                        .HasColumnType("integer");

                    b.PrimitiveCollection<List<string>>("ExtendedGenres")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.Property<DateOnly?>("ReleaseDate")
                        .HasColumnType("date");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("AddedByUserNicknameId");

                    b.HasIndex("CountryId");

                    b.HasIndex("CreatedByUserId");

                    b.ToTable("tracks", "app");
                });

            modelBuilder.Entity("Faryma.Composer.Contracts.Infrastructure.Entities.TrackGenreEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("track_genres", "app");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            Name = "электронное"
                        },
                        new
                        {
                            Id = 2L,
                            Name = "фолк"
                        },
                        new
                        {
                            Id = 3L,
                            Name = "рок"
                        },
                        new
                        {
                            Id = 4L,
                            Name = "разное"
                        },
                        new
                        {
                            Id = 5L,
                            Name = "джаз"
                        },
                        new
                        {
                            Id = 6L,
                            Name = "метал"
                        },
                        new
                        {
                            Id = 7L,
                            Name = "рэп"
                        },
                        new
                        {
                            Id = 8L,
                            Name = "поп"
                        },
                        new
                        {
                            Id = 9L,
                            Name = "оркестровый"
                        },
                        new
                        {
                            Id = 10L,
                            Name = "фанк"
                        },
                        new
                        {
                            Id = 11L,
                            Name = "мюзикл/опера"
                        },
                        new
                        {
                            Id = 12L,
                            Name = "инди"
                        },
                        new
                        {
                            Id = 13L,
                            Name = "поп-рок"
                        },
                        new
                        {
                            Id = 14L,
                            Name = "шансон"
                        },
                        new
                        {
                            Id = 15L,
                            Name = "специфическое"
                        },
                        new
                        {
                            Id = 16L,
                            Name = "баллада"
                        },
                        new
                        {
                            Id = 17L,
                            Name = "фортепиано"
                        },
                        new
                        {
                            Id = 18L,
                            Name = "инструментал"
                        });
                });

            modelBuilder.Entity("Faryma.Composer.Contracts.Infrastructure.Entities.TransactionEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("Credit")
                        .HasColumnType("bigint");

                    b.Property<long>("Debit")
                        .HasColumnType("bigint");

                    b.Property<TransactionKind>("Kind")
                        .HasColumnType("app.TransactionKind");

                    b.Property<long>("TransactionSourceId")
                        .HasColumnType("bigint");

                    b.Property<Guid>("UserNicknameAccountId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("TransactionSourceId");

                    b.HasIndex("UserNicknameAccountId");

                    b.ToTable("transactions", "app");
                });

            modelBuilder.Entity("Faryma.Composer.Contracts.Infrastructure.Entities.TransactionSources.TransactionSourceEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("CreatedByUserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("CreatedByUserId");

                    b.ToTable("transaction_sources", "app");

                    b.UseTptMappingStrategy();
                });

            modelBuilder.Entity("Faryma.Composer.Contracts.Infrastructure.Entities.UserEntitlementEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("Amount")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("CanceledAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Code")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Comment")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("CreatedByUserId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<UserEntitlementKind>("Kind")
                        .HasColumnType("app.UserEntitlementKind");

                    b.Property<DateTime?>("RedeemedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<UserEntitlementTarget>("Target")
                        .HasColumnType("app.UserEntitlementTarget");

                    b.Property<Guid>("UserNicknameId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasFilter("\"Code\" IS NOT NULL");

                    b.HasIndex("CreatedByUserId");

                    b.HasIndex("UserNicknameId");

                    b.ToTable("user_entitlements", "app");
                });

            modelBuilder.Entity("Faryma.Composer.Contracts.Infrastructure.Entities.UserEntitlementRedemptionEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Comment")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<long>("CoveredAmount")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("RedeemedByUserId")
                        .HasColumnType("uuid");

                    b.Property<long?>("ReviewOrderDetailedReviewPaymentId")
                        .HasColumnType("bigint");

                    b.Property<long?>("ReviewOrderId")
                        .HasColumnType("bigint");

                    b.Property<UserEntitlementTarget>("Target")
                        .HasColumnType("app.UserEntitlementTarget");

                    b.Property<long>("UserEntitlementId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("RedeemedByUserId");

                    b.HasIndex("ReviewOrderDetailedReviewPaymentId");

                    b.HasIndex("ReviewOrderId");

                    b.HasIndex("UserEntitlementId")
                        .IsUnique();

                    b.ToTable("user_entitlement_redemptions", "app");
                });

            modelBuilder.Entity("Faryma.Composer.Contracts.Infrastructure.Entities.UserEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("integer");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("boolean");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("text");

                    b.Property<string>("TwitchLogin")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("TwitchUserId")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.HasIndex("TwitchUserId")
                        .IsUnique()
                        .HasFilter("\"TwitchUserId\" IS NOT NULL");

                    b.ToTable("AspNetUsers", "app");
                });

            modelBuilder.Entity("Faryma.Composer.Contracts.Infrastructure.Entities.UserNicknameAccountEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<long>("Balance")
                        .HasColumnType("bigint");

                    b.Property<Guid>("UserNicknameId")
                        .HasColumnType("uuid");

                    b.Property<uint>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id");

                    b.HasIndex("UserNicknameId")
                        .IsUnique();

                    b.ToTable("user_nickname_accounts", "app");
                });

            modelBuilder.Entity("Faryma.Composer.Contracts.Infrastructure.Entities.UserNicknameEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Nickname")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.Property<string>("NormalizedNickname")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedNickname")
                        .IsUnique();

                    b.HasIndex("UserId");

                    b.ToTable("user_nicknames", "app");
                });

            modelBuilder.Entity("Faryma.Composer.Contracts.Infrastructure.Entities.UserTrackRatingEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Comment")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("CreatedByUserId")
                        .HasColumnType("uuid");

                    b.Property<int>("RatingValue")
                        .HasColumnType("integer");

                    b.Property<long>("TrackId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("CreatedByUserId");

                    b.HasIndex("TrackId", "CreatedByUserId")
                        .IsUnique();

                    b.ToTable("user_track_ratings", "app");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.DataProtection.EntityFrameworkCore.DataProtectionKey", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("FriendlyName")
                        .HasColumnType("text");

                    b.Property<string>("Xml")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("DataProtectionKeys", "app");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", "app");

                    b.HasData(
                        new
                        {
                            Id = new Guid("ac0b9e85-a06f-4655-822b-9c125d8d7bb4"),
                            ConcurrencyStamp = "AC0B9E85-A06F-4655-822B-9C125D8D7BB4",
                            Name = "Moderator",
                            NormalizedName = "MODERATOR"
                        },
                        new
                        {
                            Id = new Guid("9c3ddcde-24e7-458c-8d9c-1e5f424d3ddd"),
                            ConcurrencyStamp = "9C3DDCDE-24E7-458C-8D9C-1E5F424D3DDD",
                            Name = "Composer",
                            NormalizedName = "COMPOSER"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", "app");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", "app");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("text");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("text");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", "app");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", "app");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("Value")
                        .HasColumnType("text");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", "app");
                });

            modelBuilder.Entity("ReviewOrderEntityUserNicknameEntity", b =>
                {
                    b.Property<long>("ReviewOrdersId")
                        .HasColumnType("bigint");

                    b.Property<Guid>("UserNicknamesId")
                        .HasColumnType("uuid");

                    b.HasKey("ReviewOrdersId", "UserNicknamesId");

                    b.HasIndex("UserNicknamesId");

                    b.ToTable("ReviewOrderEntityUserNicknameEntity", "app");
                });

            modelBuilder.Entity("TrackArtistEntityTrackEntity", b =>
                {
                    b.Property<long>("ArtistsId")
                        .HasColumnType("bigint");

                    b.Property<long>("TracksId")
                        .HasColumnType("bigint");

                    b.HasKey("ArtistsId", "TracksId");

                    b.HasIndex("TracksId");

                    b.ToTable("TrackArtistEntityTrackEntity", "app");
                });

            modelBuilder.Entity("TrackArtistEntityUserEntity", b =>
                {
                    b.Property<long>("AssociatedArtistsId")
                        .HasColumnType("bigint");

                    b.Property<Guid>("UsersId")
                        .HasColumnType("uuid");

                    b.HasKey("AssociatedArtistsId", "UsersId");

                    b.HasIndex("UsersId");

                    b.ToTable("TrackArtistEntityUserEntity", "app");
                });

            modelBuilder.Entity("TrackEntityTrackGenreEntity", b =>
                {
                    b.Property<long>("GenresId")
                        .HasColumnType("bigint");

                    b.Property<long>("TracksId")
                        .HasColumnType("bigint");

                    b.HasKey("GenresId", "TracksId");

                    b.HasIndex("TracksId");

                    b.ToTable("TrackEntityTrackGenreEntity", "app");
                });

            modelBuilder.Entity("Faryma.Composer.Contracts.Infrastructure.Entities.TransactionSources.AccountTopUpEntity", b =>
                {
                    b.HasBaseType("Faryma.Composer.Contracts.Infrastructure.Entities.TransactionSources.TransactionSourceEntity");

                    b.Property<AccountTopUpProvider>("Provider")
                        .HasColumnType("app.AccountTopUpProvider");

                    b.Property<Guid>("UserNicknameAccountId")
                        .HasColumnType("uuid");

                    b.HasIndex("UserNicknameAccountId");

                    b.ToTable("account_top_ups", "app");
                });

            modelBuilder.Entity("Faryma.Composer.Contracts.Infrastructure.Entities.TransactionSources.ReviewOrderDetailedReviewPaymentEntity", b =>
                {
                    b.HasBaseType("Faryma.Composer.Contracts.Infrastructure.Entities.TransactionSources.TransactionSourceEntity");

                    b.Property<long>("Amount")
                        .HasColumnType("bigint");

                    b.Property<long>("ReviewOrderId")
                        .HasColumnType("bigint");

                    b.HasIndex("ReviewOrderId")
                        .IsUnique();

                    b.ToTable("review_order_detailed_review_payments", "app");
                });

            modelBuilder.Entity("Faryma.Composer.Contracts.Infrastructure.Entities.TransactionSources.ReviewOrderEntity", b =>
                {
                    b.HasBaseType("Faryma.Composer.Contracts.Infrastructure.Entities.TransactionSources.TransactionSourceEntity");

                    b.Property<string>("CancelReason")
                        .HasColumnType("text");

                    b.Property<DateTime?>("CanceledAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("CreationStreamId")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("InProgressAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsFrozen")
                        .HasColumnType("boolean");

                    b.Property<string>("MainNickname")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.Property<string>("MainNormalizedNickname")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.Property<long>("NominalAmount")
                        .HasColumnType("bigint");

                    b.Property<long>("NonPaymentCoverageAmount")
                        .HasColumnType("bigint");

                    b.Property<long>("PayableAmount")
                        .HasColumnType("bigint");

                    b.Property<string>("PricingComment")
                        .HasColumnType("text");

                    b.Property<long?>("ProcessingStreamId")
                        .HasColumnType("bigint");

                    b.Property<QueueCategory>("QueueCategory")
                        .HasColumnType("app.QueueCategory");

                    b.Property<ReviewOrderStatus>("Status")
                        .HasColumnType("app.ReviewOrderStatus");

                    b.Property<int?>("TrackDurationSeconds")
                        .HasColumnType("integer");

                    b.Property<long?>("TrackId")
                        .HasColumnType("bigint");

                    b.Property<string>("TrackUrl")
                        .HasColumnType("text");

                    b.Property<ReviewOrderType>("Type")
                        .HasColumnType("app.ReviewOrderType");

                    b.Property<string>("UserComment")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasIndex("CreationStreamId");

                    b.HasIndex("ProcessingStreamId");

                    b.HasIndex("TrackId");

                    b.ToTable("review_orders", "app");
                });

            modelBuilder.Entity("Faryma.Composer.Contracts.Infrastructure.Entities.TransactionSources.ReviewOrderExtraTimePaymentEntity", b =>
                {
                    b.HasBaseType("Faryma.Composer.Contracts.Infrastructure.Entities.TransactionSources.TransactionSourceEntity");

                    b.Property<long>("AmountPerSecond")
                        .HasColumnType("bigint");

                    b.Property<int>("ExtraDurationSeconds")
                        .HasColumnType("integer");

                    b.Property<int>("IncludedDurationSeconds")
                        .HasColumnType("integer");

                    b.Property<long>("ReviewOrderId")
                        .HasColumnType("bigint");

                    b.Property<int>("TrackDurationSeconds")
                        .HasColumnType("integer");

                    b.HasIndex("ReviewOrderId")
                        .IsUnique();

                    b.ToTable("review_order_extra_time_payments", "app");
                });

            modelBuilder.Entity("Faryma.Composer.Contracts.Infrastructure.Entities.TransactionSources.TransactionReversalEntity", b =>
                {
                    b.HasBaseType("Faryma.Composer.Contracts.Infrastructure.Entities.TransactionSources.TransactionSourceEntity");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<long>("ReversalTransactionId")
                        .HasColumnType("bigint");

                    b.Property<long>("ReversedTransactionId")
                        .HasColumnType("bigint");

                    b.HasIndex("ReversalTransactionId")
                        .IsUnique();

                    b.HasIndex("ReversedTransactionId")
                        .IsUnique();

                    b.ToTable("transaction_reversals", "app");
                });

            modelBuilder.Entity("Faryma.Composer.Contracts.Infrastructure.Entities.ComposerStreamEntity", b =>
                {
                    b.HasOne("Faryma.Composer.Contracts.Infrastructure.Entities.UserEntity", "CreatedByUser")
                        .WithMany("CreatedComposerStreams")
                        .HasForeignKey("CreatedByUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CreatedByUser");
                });

            modelBuilder.Entity("Faryma.Composer.Contracts.Infrastructure.Entities.RefreshTokenEntity", b =>
                {
                    b.HasOne("Faryma.Composer.Contracts.Infrastructure.Entities.UserEntity", "User")
                        .WithMany("RefreshTokens")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Faryma.Composer.Contracts.Infrastructure.Entities.ReviewEntity", b =>
                {
                    b.HasOne("Faryma.Composer.Contracts.Infrastructure.Entities.UserEntity", "CreatedByUser")
                        .WithMany("CreatedReviews")
                        .HasForeignKey("CreatedByUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Faryma.Composer.Contracts.Infrastructure.Entities.TransactionSources.ReviewOrderEntity", "ReviewOrder")
                        .WithOne("Review")
                        .HasForeignKey("Faryma.Composer.Contracts.Infrastructure.Entities.ReviewEntity", "ReviewOrderId");

                    b.HasOne("Faryma.Composer.Contracts.Infrastructure.Entities.TrackEntity", "Track")
                        .WithMany("Reviews")
                        .HasForeignKey("TrackId");

                    b.Navigation("CreatedByUser");

                    b.Navigation("ReviewOrder");

                    b.Navigation("Track");
                });

            modelBuilder.Entity("Faryma.Composer.Contracts.Infrastructure.Entities.TrackEntity", b =>
                {
                    b.HasOne("Faryma.Composer.Contracts.Infrastructure.Entities.UserNicknameEntity", "AddedBy")
                        .WithMany("UploadedTracks")
                        .HasForeignKey("AddedByUserNicknameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Faryma.Composer.Contracts.Infrastructure.Entities.TrackCountryEntity", "Country")
                        .WithMany("Tracks")
                        .HasForeignKey("CountryId");

                    b.HasOne("Faryma.Composer.Contracts.Infrastructure.Entities.UserEntity", "CreatedByUser")
                        .WithMany("CreatedTracks")
                        .HasForeignKey("CreatedByUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsMany("Faryma.Composer.Contracts.Infrastructure.Models.TrackTag", "Tags", b1 =>
                        {
                            b1.Property<long>("TrackEntityId");

                            b1.Property<int>("__synthesizedOrdinal")
                                .ValueGeneratedOnAdd();

                            b1.Property<string>("Meta");

                            b1.Property<string>("Name")
                                .IsRequired();

                            b1.HasKey("TrackEntityId", "__synthesizedOrdinal");

                            b1.ToTable("tracks", "app");

                            b1
                                .ToJson("Tags")
                                .HasColumnType("jsonb");

                            b1.WithOwner()
                                .HasForeignKey("TrackEntityId");
                        });

                    b.Navigation("AddedBy");

                    b.Navigation("Country");

                    b.Navigation("CreatedByUser");

                    b.Navigation("Tags");
                });

            modelBuilder.Entity("Faryma.Composer.Contracts.Infrastructure.Entities.TransactionEntity", b =>
                {
                    b.HasOne("Faryma.Composer.Contracts.Infrastructure.Entities.TransactionSources.TransactionSourceEntity", "TransactionSource")
                        .WithMany("Transactions")
                        .HasForeignKey("TransactionSourceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Faryma.Composer.Contracts.Infrastructure.Entities.UserNicknameAccountEntity", "UserNicknameAccount")
                        .WithMany("Transactions")
                        .HasForeignKey("UserNicknameAccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TransactionSource");

                    b.Navigation("UserNicknameAccount");
                });

            modelBuilder.Entity("Faryma.Composer.Contracts.Infrastructure.Entities.TransactionSources.TransactionSourceEntity", b =>
                {
                    b.HasOne("Faryma.Composer.Contracts.Infrastructure.Entities.UserEntity", "CreatedByUser")
                        .WithMany("CreatedTransactionSources")
                        .HasForeignKey("CreatedByUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CreatedByUser");
                });

            modelBuilder.Entity("Faryma.Composer.Contracts.Infrastructure.Entities.UserEntitlementEntity", b =>
                {
                    b.HasOne("Faryma.Composer.Contracts.Infrastructure.Entities.UserEntity", "CreatedByUser")
                        .WithMany("CreatedUserEntitlements")
                        .HasForeignKey("CreatedByUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Faryma.Composer.Contracts.Infrastructure.Entities.UserNicknameEntity", "UserNickname")
                        .WithMany("Entitlements")
                        .HasForeignKey("UserNicknameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CreatedByUser");

                    b.Navigation("UserNickname");
                });

            modelBuilder.Entity("Faryma.Composer.Contracts.Infrastructure.Entities.UserEntitlementRedemptionEntity", b =>
                {
                    b.HasOne("Faryma.Composer.Contracts.Infrastructure.Entities.UserEntity", "RedeemedByUser")
                        .WithMany("RedeemedUserEntitlements")
                        .HasForeignKey("RedeemedByUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Faryma.Composer.Contracts.Infrastructure.Entities.TransactionSources.ReviewOrderDetailedReviewPaymentEntity", "ReviewOrderDetailedReviewPayment")
                        .WithMany()
                        .HasForeignKey("ReviewOrderDetailedReviewPaymentId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Faryma.Composer.Contracts.Infrastructure.Entities.TransactionSources.ReviewOrderEntity", "ReviewOrder")
                        .WithMany("CoverageRedemptions")
                        .HasForeignKey("ReviewOrderId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Faryma.Composer.Contracts.Infrastructure.Entities.UserEntitlementEntity", "UserEntitlement")
                        .WithOne("Redemption")
                        .HasForeignKey("Faryma.Composer.Contracts.Infrastructure.Entities.UserEntitlementRedemptionEntity", "UserEntitlementId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("RedeemedByUser");

                    b.Navigation("ReviewOrder");

                    b.Navigation("ReviewOrderDetailedReviewPayment");

                    b.Navigation("UserEntitlement");
                });

            modelBuilder.Entity("Faryma.Composer.Contracts.Infrastructure.Entities.UserNicknameAccountEntity", b =>
                {
                    b.HasOne("Faryma.Composer.Contracts.Infrastructure.Entities.UserNicknameEntity", "UserNickname")
                        .WithOne("Account")
                        .HasForeignKey("Faryma.Composer.Contracts.Infrastructure.Entities.UserNicknameAccountEntity", "UserNicknameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("UserNickname");
                });

            modelBuilder.Entity("Faryma.Composer.Contracts.Infrastructure.Entities.UserNicknameEntity", b =>
                {
                    b.HasOne("Faryma.Composer.Contracts.Infrastructure.Entities.UserEntity", "User")
                        .WithMany("UserNicknames")
                        .HasForeignKey("UserId");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Faryma.Composer.Contracts.Infrastructure.Entities.UserTrackRatingEntity", b =>
                {
                    b.HasOne("Faryma.Composer.Contracts.Infrastructure.Entities.UserEntity", "CreatedByUser")
                        .WithMany("TrackRatings")
                        .HasForeignKey("CreatedByUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Faryma.Composer.Contracts.Infrastructure.Entities.TrackEntity", "Track")
                        .WithMany("UserRatings")
                        .HasForeignKey("TrackId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CreatedByUser");

                    b.Navigation("Track");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.HasOne("Faryma.Composer.Contracts.Infrastructure.Entities.UserEntity", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.HasOne("Faryma.Composer.Contracts.Infrastructure.Entities.UserEntity", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Faryma.Composer.Contracts.Infrastructure.Entities.UserEntity", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.HasOne("Faryma.Composer.Contracts.Infrastructure.Entities.UserEntity", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ReviewOrderEntityUserNicknameEntity", b =>
                {
                    b.HasOne("Faryma.Composer.Contracts.Infrastructure.Entities.TransactionSources.ReviewOrderEntity", null)
                        .WithMany()
                        .HasForeignKey("ReviewOrdersId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Faryma.Composer.Contracts.Infrastructure.Entities.UserNicknameEntity", null)
                        .WithMany()
                        .HasForeignKey("UserNicknamesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("TrackArtistEntityTrackEntity", b =>
                {
                    b.HasOne("Faryma.Composer.Contracts.Infrastructure.Entities.TrackArtistEntity", null)
                        .WithMany()
                        .HasForeignKey("ArtistsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Faryma.Composer.Contracts.Infrastructure.Entities.TrackEntity", null)
                        .WithMany()
                        .HasForeignKey("TracksId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("TrackArtistEntityUserEntity", b =>
                {
                    b.HasOne("Faryma.Composer.Contracts.Infrastructure.Entities.TrackArtistEntity", null)
                        .WithMany()
                        .HasForeignKey("AssociatedArtistsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Faryma.Composer.Contracts.Infrastructure.Entities.UserEntity", null)
                        .WithMany()
                        .HasForeignKey("UsersId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("TrackEntityTrackGenreEntity", b =>
                {
                    b.HasOne("Faryma.Composer.Contracts.Infrastructure.Entities.TrackGenreEntity", null)
                        .WithMany()
                        .HasForeignKey("GenresId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Faryma.Composer.Contracts.Infrastructure.Entities.TrackEntity", null)
                        .WithMany()
                        .HasForeignKey("TracksId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Faryma.Composer.Contracts.Infrastructure.Entities.TransactionSources.AccountTopUpEntity", b =>
                {
                    b.HasOne("Faryma.Composer.Contracts.Infrastructure.Entities.TransactionSources.TransactionSourceEntity", null)
                        .WithOne()
                        .HasForeignKey("Faryma.Composer.Contracts.Infrastructure.Entities.TransactionSources.AccountTopUpEntity", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Faryma.Composer.Contracts.Infrastructure.Entities.UserNicknameAccountEntity", "UserNicknameAccount")
                        .WithMany()
                        .HasForeignKey("UserNicknameAccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("UserNicknameAccount");
                });

            modelBuilder.Entity("Faryma.Composer.Contracts.Infrastructure.Entities.TransactionSources.ReviewOrderDetailedReviewPaymentEntity", b =>
                {
                    b.HasOne("Faryma.Composer.Contracts.Infrastructure.Entities.TransactionSources.TransactionSourceEntity", null)
                        .WithOne()
                        .HasForeignKey("Faryma.Composer.Contracts.Infrastructure.Entities.TransactionSources.ReviewOrderDetailedReviewPaymentEntity", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Faryma.Composer.Contracts.Infrastructure.Entities.TransactionSources.ReviewOrderEntity", "ReviewOrder")
                        .WithOne("DetailedReviewPayment")
                        .HasForeignKey("Faryma.Composer.Contracts.Infrastructure.Entities.TransactionSources.ReviewOrderDetailedReviewPaymentEntity", "ReviewOrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ReviewOrder");
                });

            modelBuilder.Entity("Faryma.Composer.Contracts.Infrastructure.Entities.TransactionSources.ReviewOrderEntity", b =>
                {
                    b.HasOne("Faryma.Composer.Contracts.Infrastructure.Entities.ComposerStreamEntity", "CreationStream")
                        .WithMany("CreatedReviewOrders")
                        .HasForeignKey("CreationStreamId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Faryma.Composer.Contracts.Infrastructure.Entities.TransactionSources.TransactionSourceEntity", null)
                        .WithOne()
                        .HasForeignKey("Faryma.Composer.Contracts.Infrastructure.Entities.TransactionSources.ReviewOrderEntity", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Faryma.Composer.Contracts.Infrastructure.Entities.ComposerStreamEntity", "ProcessingStream")
                        .WithMany("ProcessedReviewOrders")
                        .HasForeignKey("ProcessingStreamId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Faryma.Composer.Contracts.Infrastructure.Entities.TrackEntity", "Track")
                        .WithMany("ReviewOrders")
                        .HasForeignKey("TrackId");

                    b.Navigation("CreationStream");

                    b.Navigation("ProcessingStream");

                    b.Navigation("Track");
                });

            modelBuilder.Entity("Faryma.Composer.Contracts.Infrastructure.Entities.TransactionSources.ReviewOrderExtraTimePaymentEntity", b =>
                {
                    b.HasOne("Faryma.Composer.Contracts.Infrastructure.Entities.TransactionSources.TransactionSourceEntity", null)
                        .WithOne()
                        .HasForeignKey("Faryma.Composer.Contracts.Infrastructure.Entities.TransactionSources.ReviewOrderExtraTimePaymentEntity", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Faryma.Composer.Contracts.Infrastructure.Entities.TransactionSources.ReviewOrderEntity", "ReviewOrder")
                        .WithOne("ExtraTimePayment")
                        .HasForeignKey("Faryma.Composer.Contracts.Infrastructure.Entities.TransactionSources.ReviewOrderExtraTimePaymentEntity", "ReviewOrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ReviewOrder");
                });

            modelBuilder.Entity("Faryma.Composer.Contracts.Infrastructure.Entities.TransactionSources.TransactionReversalEntity", b =>
                {
                    b.HasOne("Faryma.Composer.Contracts.Infrastructure.Entities.TransactionSources.TransactionSourceEntity", null)
                        .WithOne()
                        .HasForeignKey("Faryma.Composer.Contracts.Infrastructure.Entities.TransactionSources.TransactionReversalEntity", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Faryma.Composer.Contracts.Infrastructure.Entities.TransactionEntity", "ReversalTransaction")
                        .WithMany()
                        .HasForeignKey("ReversalTransactionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Faryma.Composer.Contracts.Infrastructure.Entities.TransactionEntity", "ReversedTransaction")
                        .WithMany()
                        .HasForeignKey("ReversedTransactionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ReversalTransaction");

                    b.Navigation("ReversedTransaction");
                });

            modelBuilder.Entity("Faryma.Composer.Contracts.Infrastructure.Entities.ComposerStreamEntity", b =>
                {
                    b.Navigation("CreatedReviewOrders");

                    b.Navigation("ProcessedReviewOrders");
                });

            modelBuilder.Entity("Faryma.Composer.Contracts.Infrastructure.Entities.TrackCountryEntity", b =>
                {
                    b.Navigation("Tracks");
                });

            modelBuilder.Entity("Faryma.Composer.Contracts.Infrastructure.Entities.TrackEntity", b =>
                {
                    b.Navigation("ReviewOrders");

                    b.Navigation("Reviews");

                    b.Navigation("UserRatings");
                });

            modelBuilder.Entity("Faryma.Composer.Contracts.Infrastructure.Entities.TransactionSources.TransactionSourceEntity", b =>
                {
                    b.Navigation("Transactions");
                });

            modelBuilder.Entity("Faryma.Composer.Contracts.Infrastructure.Entities.UserEntitlementEntity", b =>
                {
                    b.Navigation("Redemption");
                });

            modelBuilder.Entity("Faryma.Composer.Contracts.Infrastructure.Entities.UserEntity", b =>
                {
                    b.Navigation("CreatedComposerStreams");

                    b.Navigation("CreatedReviews");

                    b.Navigation("CreatedTracks");

                    b.Navigation("CreatedTransactionSources");

                    b.Navigation("CreatedUserEntitlements");

                    b.Navigation("RedeemedUserEntitlements");

                    b.Navigation("RefreshTokens");

                    b.Navigation("TrackRatings");

                    b.Navigation("UserNicknames");
                });

            modelBuilder.Entity("Faryma.Composer.Contracts.Infrastructure.Entities.UserNicknameAccountEntity", b =>
                {
                    b.Navigation("Transactions");
                });

            modelBuilder.Entity("Faryma.Composer.Contracts.Infrastructure.Entities.UserNicknameEntity", b =>
                {
                    b.Navigation("Account")
                        .IsRequired();

                    b.Navigation("Entitlements");

                    b.Navigation("UploadedTracks");
                });

            modelBuilder.Entity("Faryma.Composer.Contracts.Infrastructure.Entities.TransactionSources.ReviewOrderEntity", b =>
                {
                    b.Navigation("CoverageRedemptions");

                    b.Navigation("DetailedReviewPayment");

                    b.Navigation("ExtraTimePayment");

                    b.Navigation("Review");
                });
#pragma warning restore 612, 618
        }
    }
}
