<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Faryma.Composer.Application.SharedContracts\Faryma.Composer.Application.SharedContracts.csproj" />
    <ProjectReference Include="..\Faryma.Composer.Domain\Faryma.Composer.Domain.csproj" />
  </ItemGroup>

</Project>
