/* tslint:disable */
/* eslint-disable */
/**
 * Faryma.Composer.Api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from './configuration';
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction } from './common';
import type { RequestArgs } from './base';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, BaseAPI, RequiredError, operationServerMap } from './base';

/**
 * Запрос добавления в заказ ссылки на трек
 */
export interface AddTrackUrlRequest {
    /**
     * Id заказа разбора трека
     */
    'reviewOrderId': number;
    /**
     * Ссылка на трек
     */
    'trackUrl': string;
}
/**
 * Ответ на запрос добавления в заказ ссылки на трек
 */
export interface AddTrackUrlResponse {
    /**
     * Заказ разбора трека
     */
    'reviewOrder': ReviewOrderDto;
}
/**
 * Настройки приложения
 */
export interface AppSettingsDto {
    /**
     * Номинальная стоимость заказа
     */
    'reviewOrderNominalAmount': number;
}
/**
 * Запрос отмены заказа
 */
export interface CancelReviewOrderRequest {
    /**
     * Id заказа разбора трека
     */
    'reviewOrderId': number;
}
/**
 * Ответ на запрос отмены заказа
 */
export interface CancelReviewOrderResponse {
    /**
     * Заказ разбора трека
     */
    'reviewOrder': ReviewOrderDto;
}
/**
 * Запрос отмены стрима
 */
export interface CancelStreamRequest {
    /**
     * Id стрима
     */
    'composerStreamId': number;
}
/**
 * Ответ на запрос отмены стрима
 */
export interface CancelStreamResponse {
    /**
     * Стрим композитора
     */
    'composerStream': ComposerStreamDto;
}
/**
 * Запрос выполнения заказа
 */
export interface CompleteReviewOrderRequest {
    /**
     * Id заказа разбора трека
     */
    'reviewOrderId': number;
    /**
     * Оценка трека (0-26)
     */
    'rating': number;
}
/**
 * Ответ на запрос выполнения заказа
 */
export interface CompleteReviewOrderResponse {
    /**
     * Заказ разбора трека
     */
    'reviewOrder': ReviewOrderDto;
    /**
     * Id созданного разбора
     */
    'reviewId': number;
}
/**
 * Запрос завершения стрима
 */
export interface CompleteStreamRequest {
    /**
     * Id стрима
     */
    'composerStreamId': number;
}
/**
 * Ответ на запрос завершения стрима
 */
export interface CompleteStreamResponse {
    /**
     * Стрим композитора
     */
    'composerStream': ComposerStreamDto;
}
/**
 * Стрим композитора
 */
export interface ComposerStreamDto {
    /**
     * Id стрима
     */
    'id': number;
    /**
     * Дата проведения стрима
     */
    'eventDate': string;
    /**
     * Статус стрима
     */
    'status': ComposerStreamStatus;
    /**
     * Тип стрима
     */
    'type': ComposerStreamType;
    /**
     * Дата и время начала стрима
     */
    'startedAt': string | null;
    /**
     * Дата и время завершения стрима
     */
    'completedAt': string | null;
}


/**
 * Статус стрима
 */

export const ComposerStreamStatus = {
    Unspecified: 'Unspecified',
    Planned: 'Planned',
    Live: 'Live',
    Completed: 'Completed',
    Canceled: 'Canceled'
} as const;

export type ComposerStreamStatus = typeof ComposerStreamStatus[keyof typeof ComposerStreamStatus];


/**
 * Тип стрима
 */

export const ComposerStreamType = {
    Unspecified: 'Unspecified',
    Donation: 'Donation',
    Debt: 'Debt',
    Charity: 'Charity'
} as const;

export type ComposerStreamType = typeof ComposerStreamType[keyof typeof ComposerStreamType];


/**
 * Запрос создания заказа на разбор
 */
export interface CreateReviewOrderRequest {
    /**
     * Псевдоним пользователя
     */
    'nickname': string;
    /**
     * Тип заказа разбора трека
     */
    'orderType': ReviewOrderType;
    /**
     * Ссылка на трек
     */
    'trackUrl'?: string | null;
    /**
     * Сумма платежа
     */
    'paymentAmount'?: number | null;
    /**
     * Комментарий пользователя
     */
    'userComment'?: string | null;
}


/**
 * Ответ на запрос создания заказа на разбор
 */
export interface CreateReviewOrderResponse {
    /**
     * Заказ разбора трека
     */
    'reviewOrder': ReviewOrderDto;
}
/**
 * Запрос создания стрима
 */
export interface CreateStreamRequest {
    /**
     * Дата проведения стрима
     */
    'eventDate': string;
    /**
     * Тип стрима
     */
    'type': ComposerStreamType;
}


/**
 * Ответ на запрос создания стрима
 */
export interface CreateStreamResponse {
    /**
     * Стрим композитора
     */
    'composerStream': ComposerStreamDto;
}
/**
 * Ответ на запрос текущего и запланированных стримов
 */
export interface FindLiveAndPlannedStreamsResponse {
    /**
     * Список стримов
     */
    'streams': Array<ComposerStreamDto>;
}
/**
 * Ответ на запрос поиска стримов
 */
export interface FindStreamsResponse {
    /**
     * Список стримов
     */
    'streams': Array<ComposerStreamDto>;
}
/**
 * Запрос заморозки заказа
 */
export interface FreezeReviewOrderRequest {
    /**
     * Id заказа разбора трека
     */
    'reviewOrderId': number;
}
/**
 * Ответ на запрос заморозки заказа
 */
export interface FreezeReviewOrderResponse {
    /**
     * Заказ разбора трека
     */
    'reviewOrder': ReviewOrderDto;
}
/**
 * Ответ на запрос получения очереди заказов
 */
export interface GetOrderQueueResponse {
    /**
     * Версия для синхронизации состояния очереди
     */
    'syncVersion': number;
    /**
     * Активные заказы
     */
    'activeOrders': Array<OrderPositionDto>;
    /**
     * Заказ в работе
     */
    'inProgressOrder'?: OrderPositionDto | null;
    /**
     * Выполненные заказы
     */
    'completedOrders': Array<OrderPositionDto>;
    /**
     * Запланированные заказы
     */
    'scheduledOrders': Array<OrderPositionDto>;
    /**
     * Замороженные заказы
     */
    'frozenOrders': Array<OrderPositionDto>;
}
/**
 * Запрос входа в систему
 */
export interface LoginRequest {
    /**
     * Имя пользователя
     */
    'userName': string;
    /**
     * Пароль
     */
    'password': string;
}
/**
 * Ответ на запрос входа в систему
 */
export interface LoginResponse {
    /**
     * JWT-токен
     */
    'token': string;
}
/**
 * Запрос поднятия заказа в очереди
 */
export interface MoveUpReviewOrderRequest {
    /**
     * Псевдоним пользователя
     */
    'nickname': string;
    /**
     * Id заказа разбора трека
     */
    'reviewOrderId': number;
    /**
     * Сумма платежа
     */
    'paymentAmount': number;
}
/**
 * Ответ на запрос поднятия заказа в очереди
 */
export interface MoveUpReviewOrderResponse {
    /**
     * Заказ разбора трека
     */
    'reviewOrder': ReviewOrderDto;
    /**
     * Id платежа
     */
    'paymentTransactionId': number;
}

export const OrderActivityStatus = {
    Unspecified: 'Unspecified',
    Active: 'Active',
    InProgress: 'InProgress',
    Completed: 'Completed',
    Scheduled: 'Scheduled',
    Frozen: 'Frozen',
    Removed: 'Removed'
} as const;

export type OrderActivityStatus = typeof OrderActivityStatus[keyof typeof OrderActivityStatus];


/**
 * Тип категории заказа
 */

export const OrderCategoryType = {
    Unspecified: 'Unspecified',
    OutOfQueue: 'OutOfQueue',
    Donation: 'Donation',
    Debt: 'Debt'
} as const;

export type OrderCategoryType = typeof OrderCategoryType[keyof typeof OrderCategoryType];


/**
 * Представляет позицию заказа в очереди, включая сам заказ и историю перемещений
 */
export interface OrderPositionDto {
    /**
     * Заказ разбора трека
     */
    'order': ReviewOrderDto;
    /**
     * Предыдущая позиция заказа в очереди
     */
    'previousPosition': OrderQueuePositionDto;
    /**
     * Текущая позиция заказа в очереди
     */
    'currentPosition': OrderQueuePositionDto;
}
/**
 * Позиция заказа в очереди, включая его индекс, статус активности и категорию
 */
export interface OrderQueuePositionDto {
    /**
     * Позиция заказа в очереди
     */
    'queueIndex': number;
    /**
     * Статус активности заказа
     */
    'activityStatus': OrderActivityStatus;
    /**
     * Тип категории заказа
     */
    'categoryType': OrderCategoryType;
    /**
     * Индекс категории, если заказ относится к долговой категории
     */
    'categoryDebtIndex': number;
}


/**
 * Запрос регистрации пользователя
 */
export interface RegisterRequest {
    /**
     * Имя пользователя
     */
    'userName': string;
    /**
     * Пароль
     */
    'password': string;
}
/**
 * Заказ разбора трека
 */
export interface ReviewOrderDto {
    /**
     * Id заказа
     */
    'id': number;
    /**
     * Дата и время создания заказа
     */
    'createdAt': string;
    /**
     * Дата и время взятия заказа в работу
     */
    'inProgressAt': string | null;
    /**
     * Дата и время выполнения заказа
     */
    'completedAt': string | null;
    /**
     * Тип заказа разбора трека
     */
    'type': ReviewOrderType;
    /**
     * Тип категории заказа
     */
    'categoryType': OrderCategoryType;
    /**
     * Статус заказа разбора трека
     */
    'status': ReviewOrderStatus;
    /**
     * Заказ заморожен
     */
    'isFrozen': boolean;
    /**
     * Ссылка на трек
     */
    'trackUrl': string | null;
    /**
     * Комментарий пользователя
     */
    'userComment': string | null;
    /**
     * Основной ник пользователя, из всех пользователей, кто причастен к созданию заказа
     */
    'mainNickname': string;
    /**
     * Общая стоимость заказа (номинал + платежи)
     */
    'totalAmount': number;
    /**
     * Связанный cтрим композитора, где создан заказ
     */
    'creationStream': ComposerStreamDto;
}


/**
 * Статус заказа разбора трека
 */

export const ReviewOrderStatus = {
    Unspecified: 'Unspecified',
    Preorder: 'Preorder',
    Pending: 'Pending',
    InProgress: 'InProgress',
    Completed: 'Completed',
    Canceled: 'Canceled'
} as const;

export type ReviewOrderStatus = typeof ReviewOrderStatus[keyof typeof ReviewOrderStatus];


/**
 * Тип заказа разбора трека
 */

export const ReviewOrderType = {
    Unspecified: 'Unspecified',
    OutOfQueue: 'OutOfQueue',
    Donation: 'Donation',
    Free: 'Free',
    Charity: 'Charity',
    Custom: 'Custom'
} as const;

export type ReviewOrderType = typeof ReviewOrderType[keyof typeof ReviewOrderType];


/**
 * Запрос запуска стрима
 */
export interface StartStreamRequest {
    /**
     * Id стрима
     */
    'composerStreamId': number;
}
/**
 * Ответ на запрос запуска стрима
 */
export interface StartStreamResponse {
    /**
     * Стрим композитора
     */
    'composerStream': ComposerStreamDto;
}
/**
 * Запрос взятия заказа в работу
 */
export interface TakeOrderInProgressRequest {
    /**
     * Id заказа разбора трека
     */
    'reviewOrderId': number;
}
/**
 * Ответ на запрос взятия заказа в работу
 */
export interface TakeOrderInProgressResponse {
    /**
     * Заказ разбора трека
     */
    'reviewOrder': ReviewOrderDto;
}
/**
 * Запрос разморозки заказа
 */
export interface UnfreezeReviewOrderRequest {
    /**
     * Id заказа разбора трека
     */
    'reviewOrderId': number;
}
/**
 * Ответ на запрос разморозки заказа
 */
export interface UnfreezeReviewOrderResponse {
    /**
     * Заказ разбора трека
     */
    'reviewOrder': ReviewOrderDto;
}

/**
 * AppSettingsApi - axios parameter creator
 */
export const AppSettingsApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @summary Возвращает текущие настройки
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiAppSettingsGetAppSettingsGet: async (options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/api/AppSettings/GetAppSettings`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication Bearer required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Обновляет настройки
         * @param {AppSettingsDto} [appSettingsDto] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiAppSettingsUpdateAppSettingsPost: async (appSettingsDto?: AppSettingsDto, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/api/AppSettings/UpdateAppSettings`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication Bearer required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(appSettingsDto, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * AppSettingsApi - functional programming interface
 */
export const AppSettingsApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = AppSettingsApiAxiosParamCreator(configuration)
    return {
        /**
         * 
         * @summary Возвращает текущие настройки
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async apiAppSettingsGetAppSettingsGet(options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<AppSettingsDto>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.apiAppSettingsGetAppSettingsGet(options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['AppSettingsApi.apiAppSettingsGetAppSettingsGet']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Обновляет настройки
         * @param {AppSettingsDto} [appSettingsDto] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async apiAppSettingsUpdateAppSettingsPost(appSettingsDto?: AppSettingsDto, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<AppSettingsDto>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.apiAppSettingsUpdateAppSettingsPost(appSettingsDto, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['AppSettingsApi.apiAppSettingsUpdateAppSettingsPost']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * AppSettingsApi - factory interface
 */
export const AppSettingsApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = AppSettingsApiFp(configuration)
    return {
        /**
         * 
         * @summary Возвращает текущие настройки
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiAppSettingsGetAppSettingsGet(options?: RawAxiosRequestConfig): AxiosPromise<AppSettingsDto> {
            return localVarFp.apiAppSettingsGetAppSettingsGet(options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Обновляет настройки
         * @param {AppSettingsDto} [appSettingsDto] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiAppSettingsUpdateAppSettingsPost(appSettingsDto?: AppSettingsDto, options?: RawAxiosRequestConfig): AxiosPromise<AppSettingsDto> {
            return localVarFp.apiAppSettingsUpdateAppSettingsPost(appSettingsDto, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * AppSettingsApi - object-oriented interface
 */
export class AppSettingsApi extends BaseAPI {
    /**
     * 
     * @summary Возвращает текущие настройки
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public apiAppSettingsGetAppSettingsGet(options?: RawAxiosRequestConfig) {
        return AppSettingsApiFp(this.configuration).apiAppSettingsGetAppSettingsGet(options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Обновляет настройки
     * @param {AppSettingsDto} [appSettingsDto] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public apiAppSettingsUpdateAppSettingsPost(appSettingsDto?: AppSettingsDto, options?: RawAxiosRequestConfig) {
        return AppSettingsApiFp(this.configuration).apiAppSettingsUpdateAppSettingsPost(appSettingsDto, options).then((request) => request(this.axios, this.basePath));
    }
}



/**
 * AuthApi - axios parameter creator
 */
export const AuthApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @summary Выполняет аутентификацию пользователя и возвращает JWT токен
         * @param {LoginRequest} [loginRequest] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiAuthLoginPost: async (loginRequest?: LoginRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/api/Auth/Login`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication Bearer required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(loginRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Регистрирует нового пользователя в системе
         * @param {RegisterRequest} [registerRequest] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiAuthRegisterPost: async (registerRequest?: RegisterRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/api/Auth/Register`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication Bearer required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(registerRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * AuthApi - functional programming interface
 */
export const AuthApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = AuthApiAxiosParamCreator(configuration)
    return {
        /**
         * 
         * @summary Выполняет аутентификацию пользователя и возвращает JWT токен
         * @param {LoginRequest} [loginRequest] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async apiAuthLoginPost(loginRequest?: LoginRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<LoginResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.apiAuthLoginPost(loginRequest, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['AuthApi.apiAuthLoginPost']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Регистрирует нового пользователя в системе
         * @param {RegisterRequest} [registerRequest] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async apiAuthRegisterPost(registerRequest?: RegisterRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.apiAuthRegisterPost(registerRequest, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['AuthApi.apiAuthRegisterPost']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * AuthApi - factory interface
 */
export const AuthApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = AuthApiFp(configuration)
    return {
        /**
         * 
         * @summary Выполняет аутентификацию пользователя и возвращает JWT токен
         * @param {LoginRequest} [loginRequest] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiAuthLoginPost(loginRequest?: LoginRequest, options?: RawAxiosRequestConfig): AxiosPromise<LoginResponse> {
            return localVarFp.apiAuthLoginPost(loginRequest, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Регистрирует нового пользователя в системе
         * @param {RegisterRequest} [registerRequest] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiAuthRegisterPost(registerRequest?: RegisterRequest, options?: RawAxiosRequestConfig): AxiosPromise<void> {
            return localVarFp.apiAuthRegisterPost(registerRequest, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * AuthApi - object-oriented interface
 */
export class AuthApi extends BaseAPI {
    /**
     * 
     * @summary Выполняет аутентификацию пользователя и возвращает JWT токен
     * @param {LoginRequest} [loginRequest] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public apiAuthLoginPost(loginRequest?: LoginRequest, options?: RawAxiosRequestConfig) {
        return AuthApiFp(this.configuration).apiAuthLoginPost(loginRequest, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Регистрирует нового пользователя в системе
     * @param {RegisterRequest} [registerRequest] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public apiAuthRegisterPost(registerRequest?: RegisterRequest, options?: RawAxiosRequestConfig) {
        return AuthApiFp(this.configuration).apiAuthRegisterPost(registerRequest, options).then((request) => request(this.axios, this.basePath));
    }
}



/**
 * ComposerStreamApi - axios parameter creator
 */
export const ComposerStreamApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @summary Отменяет стрим
         * @param {CancelStreamRequest} [cancelStreamRequest] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiComposerStreamCancelStreamPost: async (cancelStreamRequest?: CancelStreamRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/api/ComposerStream/CancelStream`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication Bearer required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(cancelStreamRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Завершает стрим
         * @param {CompleteStreamRequest} [completeStreamRequest] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiComposerStreamCompleteStreamPost: async (completeStreamRequest?: CompleteStreamRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/api/ComposerStream/CompleteStream`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication Bearer required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(completeStreamRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Создает стрим
         * @param {CreateStreamRequest} [createStreamRequest] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiComposerStreamCreateStreamPost: async (createStreamRequest?: CreateStreamRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/api/ComposerStream/CreateStream`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication Bearer required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(createStreamRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Возвращает текущий и запланированные стримы
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiComposerStreamFindLiveAndPlannedGet: async (options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/api/ComposerStream/FindLiveAndPlanned`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication Bearer required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Возвращает список стримов
         * @param {string} dateFrom Начальная дата периода поиска
         * @param {string} dateTo Конечная дата периода поиска
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiComposerStreamFindStreamsGet: async (dateFrom: string, dateTo: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'dateFrom' is not null or undefined
            assertParamExists('apiComposerStreamFindStreamsGet', 'dateFrom', dateFrom)
            // verify required parameter 'dateTo' is not null or undefined
            assertParamExists('apiComposerStreamFindStreamsGet', 'dateTo', dateTo)
            const localVarPath = `/api/ComposerStream/FindStreams`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication Bearer required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            if (dateFrom !== undefined) {
                localVarQueryParameter['DateFrom'] = (dateFrom as any instanceof Date) ?
                    (dateFrom as any).toISOString().substring(0,10) :
                    dateFrom;
            }

            if (dateTo !== undefined) {
                localVarQueryParameter['DateTo'] = (dateTo as any instanceof Date) ?
                    (dateTo as any).toISOString().substring(0,10) :
                    dateTo;
            }


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Запускает стрим
         * @param {StartStreamRequest} [startStreamRequest] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiComposerStreamStartStreamPost: async (startStreamRequest?: StartStreamRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/api/ComposerStream/StartStream`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication Bearer required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(startStreamRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * ComposerStreamApi - functional programming interface
 */
export const ComposerStreamApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = ComposerStreamApiAxiosParamCreator(configuration)
    return {
        /**
         * 
         * @summary Отменяет стрим
         * @param {CancelStreamRequest} [cancelStreamRequest] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async apiComposerStreamCancelStreamPost(cancelStreamRequest?: CancelStreamRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<CancelStreamResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.apiComposerStreamCancelStreamPost(cancelStreamRequest, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['ComposerStreamApi.apiComposerStreamCancelStreamPost']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Завершает стрим
         * @param {CompleteStreamRequest} [completeStreamRequest] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async apiComposerStreamCompleteStreamPost(completeStreamRequest?: CompleteStreamRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<CompleteStreamResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.apiComposerStreamCompleteStreamPost(completeStreamRequest, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['ComposerStreamApi.apiComposerStreamCompleteStreamPost']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Создает стрим
         * @param {CreateStreamRequest} [createStreamRequest] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async apiComposerStreamCreateStreamPost(createStreamRequest?: CreateStreamRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<CreateStreamResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.apiComposerStreamCreateStreamPost(createStreamRequest, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['ComposerStreamApi.apiComposerStreamCreateStreamPost']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Возвращает текущий и запланированные стримы
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async apiComposerStreamFindLiveAndPlannedGet(options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<FindLiveAndPlannedStreamsResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.apiComposerStreamFindLiveAndPlannedGet(options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['ComposerStreamApi.apiComposerStreamFindLiveAndPlannedGet']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Возвращает список стримов
         * @param {string} dateFrom Начальная дата периода поиска
         * @param {string} dateTo Конечная дата периода поиска
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async apiComposerStreamFindStreamsGet(dateFrom: string, dateTo: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<FindStreamsResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.apiComposerStreamFindStreamsGet(dateFrom, dateTo, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['ComposerStreamApi.apiComposerStreamFindStreamsGet']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Запускает стрим
         * @param {StartStreamRequest} [startStreamRequest] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async apiComposerStreamStartStreamPost(startStreamRequest?: StartStreamRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<StartStreamResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.apiComposerStreamStartStreamPost(startStreamRequest, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['ComposerStreamApi.apiComposerStreamStartStreamPost']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * ComposerStreamApi - factory interface
 */
export const ComposerStreamApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = ComposerStreamApiFp(configuration)
    return {
        /**
         * 
         * @summary Отменяет стрим
         * @param {CancelStreamRequest} [cancelStreamRequest] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiComposerStreamCancelStreamPost(cancelStreamRequest?: CancelStreamRequest, options?: RawAxiosRequestConfig): AxiosPromise<CancelStreamResponse> {
            return localVarFp.apiComposerStreamCancelStreamPost(cancelStreamRequest, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Завершает стрим
         * @param {CompleteStreamRequest} [completeStreamRequest] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiComposerStreamCompleteStreamPost(completeStreamRequest?: CompleteStreamRequest, options?: RawAxiosRequestConfig): AxiosPromise<CompleteStreamResponse> {
            return localVarFp.apiComposerStreamCompleteStreamPost(completeStreamRequest, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Создает стрим
         * @param {CreateStreamRequest} [createStreamRequest] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiComposerStreamCreateStreamPost(createStreamRequest?: CreateStreamRequest, options?: RawAxiosRequestConfig): AxiosPromise<CreateStreamResponse> {
            return localVarFp.apiComposerStreamCreateStreamPost(createStreamRequest, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Возвращает текущий и запланированные стримы
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiComposerStreamFindLiveAndPlannedGet(options?: RawAxiosRequestConfig): AxiosPromise<FindLiveAndPlannedStreamsResponse> {
            return localVarFp.apiComposerStreamFindLiveAndPlannedGet(options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Возвращает список стримов
         * @param {string} dateFrom Начальная дата периода поиска
         * @param {string} dateTo Конечная дата периода поиска
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiComposerStreamFindStreamsGet(dateFrom: string, dateTo: string, options?: RawAxiosRequestConfig): AxiosPromise<FindStreamsResponse> {
            return localVarFp.apiComposerStreamFindStreamsGet(dateFrom, dateTo, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Запускает стрим
         * @param {StartStreamRequest} [startStreamRequest] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiComposerStreamStartStreamPost(startStreamRequest?: StartStreamRequest, options?: RawAxiosRequestConfig): AxiosPromise<StartStreamResponse> {
            return localVarFp.apiComposerStreamStartStreamPost(startStreamRequest, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * ComposerStreamApi - object-oriented interface
 */
export class ComposerStreamApi extends BaseAPI {
    /**
     * 
     * @summary Отменяет стрим
     * @param {CancelStreamRequest} [cancelStreamRequest] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public apiComposerStreamCancelStreamPost(cancelStreamRequest?: CancelStreamRequest, options?: RawAxiosRequestConfig) {
        return ComposerStreamApiFp(this.configuration).apiComposerStreamCancelStreamPost(cancelStreamRequest, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Завершает стрим
     * @param {CompleteStreamRequest} [completeStreamRequest] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public apiComposerStreamCompleteStreamPost(completeStreamRequest?: CompleteStreamRequest, options?: RawAxiosRequestConfig) {
        return ComposerStreamApiFp(this.configuration).apiComposerStreamCompleteStreamPost(completeStreamRequest, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Создает стрим
     * @param {CreateStreamRequest} [createStreamRequest] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public apiComposerStreamCreateStreamPost(createStreamRequest?: CreateStreamRequest, options?: RawAxiosRequestConfig) {
        return ComposerStreamApiFp(this.configuration).apiComposerStreamCreateStreamPost(createStreamRequest, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Возвращает текущий и запланированные стримы
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public apiComposerStreamFindLiveAndPlannedGet(options?: RawAxiosRequestConfig) {
        return ComposerStreamApiFp(this.configuration).apiComposerStreamFindLiveAndPlannedGet(options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Возвращает список стримов
     * @param {string} dateFrom Начальная дата периода поиска
     * @param {string} dateTo Конечная дата периода поиска
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public apiComposerStreamFindStreamsGet(dateFrom: string, dateTo: string, options?: RawAxiosRequestConfig) {
        return ComposerStreamApiFp(this.configuration).apiComposerStreamFindStreamsGet(dateFrom, dateTo, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Запускает стрим
     * @param {StartStreamRequest} [startStreamRequest] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public apiComposerStreamStartStreamPost(startStreamRequest?: StartStreamRequest, options?: RawAxiosRequestConfig) {
        return ComposerStreamApiFp(this.configuration).apiComposerStreamStartStreamPost(startStreamRequest, options).then((request) => request(this.axios, this.basePath));
    }
}



/**
 * OrderQueueApi - axios parameter creator
 */
export const OrderQueueApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @summary Получает текущее состояние очереди заказов
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiOrderQueueGetOrderQueueGet: async (options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/api/OrderQueue/GetOrderQueue`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication Bearer required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * OrderQueueApi - functional programming interface
 */
export const OrderQueueApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = OrderQueueApiAxiosParamCreator(configuration)
    return {
        /**
         * 
         * @summary Получает текущее состояние очереди заказов
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async apiOrderQueueGetOrderQueueGet(options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<GetOrderQueueResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.apiOrderQueueGetOrderQueueGet(options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['OrderQueueApi.apiOrderQueueGetOrderQueueGet']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * OrderQueueApi - factory interface
 */
export const OrderQueueApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = OrderQueueApiFp(configuration)
    return {
        /**
         * 
         * @summary Получает текущее состояние очереди заказов
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiOrderQueueGetOrderQueueGet(options?: RawAxiosRequestConfig): AxiosPromise<GetOrderQueueResponse> {
            return localVarFp.apiOrderQueueGetOrderQueueGet(options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * OrderQueueApi - object-oriented interface
 */
export class OrderQueueApi extends BaseAPI {
    /**
     * 
     * @summary Получает текущее состояние очереди заказов
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public apiOrderQueueGetOrderQueueGet(options?: RawAxiosRequestConfig) {
        return OrderQueueApiFp(this.configuration).apiOrderQueueGetOrderQueueGet(options).then((request) => request(this.axios, this.basePath));
    }
}



/**
 * ReviewOrderApi - axios parameter creator
 */
export const ReviewOrderApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @summary Добавляет или изменяет ссылку на трек
         * @param {AddTrackUrlRequest} [addTrackUrlRequest] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiReviewOrderAddTrackUrlPost: async (addTrackUrlRequest?: AddTrackUrlRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/api/ReviewOrder/AddTrackUrl`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication Bearer required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(addTrackUrlRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Отменяет заказ
         * @param {CancelReviewOrderRequest} [cancelReviewOrderRequest] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiReviewOrderCancelReviewOrderPost: async (cancelReviewOrderRequest?: CancelReviewOrderRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/api/ReviewOrder/CancelReviewOrder`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication Bearer required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(cancelReviewOrderRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Выполнение заказа
         * @param {CompleteReviewOrderRequest} [completeReviewOrderRequest] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiReviewOrderCompleteReviewOrderPost: async (completeReviewOrderRequest?: CompleteReviewOrderRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/api/ReviewOrder/CompleteReviewOrder`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication Bearer required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(completeReviewOrderRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Создает заказ
         * @param {string} [idempotencyKey] Ключ идемпотентности
         * @param {CreateReviewOrderRequest} [createReviewOrderRequest] Запрос создания заказа
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiReviewOrderCreateReviewOrderPost: async (idempotencyKey?: string, createReviewOrderRequest?: CreateReviewOrderRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/api/ReviewOrder/CreateReviewOrder`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication Bearer required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            if (idempotencyKey != null) {
                localVarHeaderParameter['Idempotency-Key'] = String(idempotencyKey);
            }
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(createReviewOrderRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Замораживает заказ
         * @param {FreezeReviewOrderRequest} [freezeReviewOrderRequest] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiReviewOrderFreezeReviewOrderPost: async (freezeReviewOrderRequest?: FreezeReviewOrderRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/api/ReviewOrder/FreezeReviewOrder`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication Bearer required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(freezeReviewOrderRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Поднимает заказ в очереди
         * @param {string} [idempotencyKey] Ключ идемпотентности
         * @param {MoveUpReviewOrderRequest} [moveUpReviewOrderRequest] Запрос поднятия заказа в очереди
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiReviewOrderMoveUpReviewOrderPost: async (idempotencyKey?: string, moveUpReviewOrderRequest?: MoveUpReviewOrderRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/api/ReviewOrder/MoveUpReviewOrder`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication Bearer required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            if (idempotencyKey != null) {
                localVarHeaderParameter['Idempotency-Key'] = String(idempotencyKey);
            }
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(moveUpReviewOrderRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Взятие заказа в работу
         * @param {TakeOrderInProgressRequest} [takeOrderInProgressRequest] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiReviewOrderTakeOrderInProgressPost: async (takeOrderInProgressRequest?: TakeOrderInProgressRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/api/ReviewOrder/TakeOrderInProgress`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication Bearer required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(takeOrderInProgressRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Размораживает заказ
         * @param {UnfreezeReviewOrderRequest} [unfreezeReviewOrderRequest] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiReviewOrderUnfreezeReviewOrderPost: async (unfreezeReviewOrderRequest?: UnfreezeReviewOrderRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/api/ReviewOrder/UnfreezeReviewOrder`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication Bearer required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(unfreezeReviewOrderRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * ReviewOrderApi - functional programming interface
 */
export const ReviewOrderApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = ReviewOrderApiAxiosParamCreator(configuration)
    return {
        /**
         * 
         * @summary Добавляет или изменяет ссылку на трек
         * @param {AddTrackUrlRequest} [addTrackUrlRequest] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async apiReviewOrderAddTrackUrlPost(addTrackUrlRequest?: AddTrackUrlRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<AddTrackUrlResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.apiReviewOrderAddTrackUrlPost(addTrackUrlRequest, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['ReviewOrderApi.apiReviewOrderAddTrackUrlPost']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Отменяет заказ
         * @param {CancelReviewOrderRequest} [cancelReviewOrderRequest] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async apiReviewOrderCancelReviewOrderPost(cancelReviewOrderRequest?: CancelReviewOrderRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<CancelReviewOrderResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.apiReviewOrderCancelReviewOrderPost(cancelReviewOrderRequest, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['ReviewOrderApi.apiReviewOrderCancelReviewOrderPost']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Выполнение заказа
         * @param {CompleteReviewOrderRequest} [completeReviewOrderRequest] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async apiReviewOrderCompleteReviewOrderPost(completeReviewOrderRequest?: CompleteReviewOrderRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<CompleteReviewOrderResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.apiReviewOrderCompleteReviewOrderPost(completeReviewOrderRequest, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['ReviewOrderApi.apiReviewOrderCompleteReviewOrderPost']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Создает заказ
         * @param {string} [idempotencyKey] Ключ идемпотентности
         * @param {CreateReviewOrderRequest} [createReviewOrderRequest] Запрос создания заказа
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async apiReviewOrderCreateReviewOrderPost(idempotencyKey?: string, createReviewOrderRequest?: CreateReviewOrderRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<CreateReviewOrderResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.apiReviewOrderCreateReviewOrderPost(idempotencyKey, createReviewOrderRequest, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['ReviewOrderApi.apiReviewOrderCreateReviewOrderPost']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Замораживает заказ
         * @param {FreezeReviewOrderRequest} [freezeReviewOrderRequest] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async apiReviewOrderFreezeReviewOrderPost(freezeReviewOrderRequest?: FreezeReviewOrderRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<FreezeReviewOrderResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.apiReviewOrderFreezeReviewOrderPost(freezeReviewOrderRequest, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['ReviewOrderApi.apiReviewOrderFreezeReviewOrderPost']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Поднимает заказ в очереди
         * @param {string} [idempotencyKey] Ключ идемпотентности
         * @param {MoveUpReviewOrderRequest} [moveUpReviewOrderRequest] Запрос поднятия заказа в очереди
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async apiReviewOrderMoveUpReviewOrderPost(idempotencyKey?: string, moveUpReviewOrderRequest?: MoveUpReviewOrderRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<MoveUpReviewOrderResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.apiReviewOrderMoveUpReviewOrderPost(idempotencyKey, moveUpReviewOrderRequest, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['ReviewOrderApi.apiReviewOrderMoveUpReviewOrderPost']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Взятие заказа в работу
         * @param {TakeOrderInProgressRequest} [takeOrderInProgressRequest] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async apiReviewOrderTakeOrderInProgressPost(takeOrderInProgressRequest?: TakeOrderInProgressRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<TakeOrderInProgressResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.apiReviewOrderTakeOrderInProgressPost(takeOrderInProgressRequest, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['ReviewOrderApi.apiReviewOrderTakeOrderInProgressPost']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Размораживает заказ
         * @param {UnfreezeReviewOrderRequest} [unfreezeReviewOrderRequest] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async apiReviewOrderUnfreezeReviewOrderPost(unfreezeReviewOrderRequest?: UnfreezeReviewOrderRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<UnfreezeReviewOrderResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.apiReviewOrderUnfreezeReviewOrderPost(unfreezeReviewOrderRequest, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['ReviewOrderApi.apiReviewOrderUnfreezeReviewOrderPost']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * ReviewOrderApi - factory interface
 */
export const ReviewOrderApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = ReviewOrderApiFp(configuration)
    return {
        /**
         * 
         * @summary Добавляет или изменяет ссылку на трек
         * @param {AddTrackUrlRequest} [addTrackUrlRequest] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiReviewOrderAddTrackUrlPost(addTrackUrlRequest?: AddTrackUrlRequest, options?: RawAxiosRequestConfig): AxiosPromise<AddTrackUrlResponse> {
            return localVarFp.apiReviewOrderAddTrackUrlPost(addTrackUrlRequest, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Отменяет заказ
         * @param {CancelReviewOrderRequest} [cancelReviewOrderRequest] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiReviewOrderCancelReviewOrderPost(cancelReviewOrderRequest?: CancelReviewOrderRequest, options?: RawAxiosRequestConfig): AxiosPromise<CancelReviewOrderResponse> {
            return localVarFp.apiReviewOrderCancelReviewOrderPost(cancelReviewOrderRequest, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Выполнение заказа
         * @param {CompleteReviewOrderRequest} [completeReviewOrderRequest] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiReviewOrderCompleteReviewOrderPost(completeReviewOrderRequest?: CompleteReviewOrderRequest, options?: RawAxiosRequestConfig): AxiosPromise<CompleteReviewOrderResponse> {
            return localVarFp.apiReviewOrderCompleteReviewOrderPost(completeReviewOrderRequest, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Создает заказ
         * @param {string} [idempotencyKey] Ключ идемпотентности
         * @param {CreateReviewOrderRequest} [createReviewOrderRequest] Запрос создания заказа
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiReviewOrderCreateReviewOrderPost(idempotencyKey?: string, createReviewOrderRequest?: CreateReviewOrderRequest, options?: RawAxiosRequestConfig): AxiosPromise<CreateReviewOrderResponse> {
            return localVarFp.apiReviewOrderCreateReviewOrderPost(idempotencyKey, createReviewOrderRequest, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Замораживает заказ
         * @param {FreezeReviewOrderRequest} [freezeReviewOrderRequest] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiReviewOrderFreezeReviewOrderPost(freezeReviewOrderRequest?: FreezeReviewOrderRequest, options?: RawAxiosRequestConfig): AxiosPromise<FreezeReviewOrderResponse> {
            return localVarFp.apiReviewOrderFreezeReviewOrderPost(freezeReviewOrderRequest, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Поднимает заказ в очереди
         * @param {string} [idempotencyKey] Ключ идемпотентности
         * @param {MoveUpReviewOrderRequest} [moveUpReviewOrderRequest] Запрос поднятия заказа в очереди
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiReviewOrderMoveUpReviewOrderPost(idempotencyKey?: string, moveUpReviewOrderRequest?: MoveUpReviewOrderRequest, options?: RawAxiosRequestConfig): AxiosPromise<MoveUpReviewOrderResponse> {
            return localVarFp.apiReviewOrderMoveUpReviewOrderPost(idempotencyKey, moveUpReviewOrderRequest, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Взятие заказа в работу
         * @param {TakeOrderInProgressRequest} [takeOrderInProgressRequest] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiReviewOrderTakeOrderInProgressPost(takeOrderInProgressRequest?: TakeOrderInProgressRequest, options?: RawAxiosRequestConfig): AxiosPromise<TakeOrderInProgressResponse> {
            return localVarFp.apiReviewOrderTakeOrderInProgressPost(takeOrderInProgressRequest, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Размораживает заказ
         * @param {UnfreezeReviewOrderRequest} [unfreezeReviewOrderRequest] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiReviewOrderUnfreezeReviewOrderPost(unfreezeReviewOrderRequest?: UnfreezeReviewOrderRequest, options?: RawAxiosRequestConfig): AxiosPromise<UnfreezeReviewOrderResponse> {
            return localVarFp.apiReviewOrderUnfreezeReviewOrderPost(unfreezeReviewOrderRequest, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * ReviewOrderApi - object-oriented interface
 */
export class ReviewOrderApi extends BaseAPI {
    /**
     * 
     * @summary Добавляет или изменяет ссылку на трек
     * @param {AddTrackUrlRequest} [addTrackUrlRequest] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public apiReviewOrderAddTrackUrlPost(addTrackUrlRequest?: AddTrackUrlRequest, options?: RawAxiosRequestConfig) {
        return ReviewOrderApiFp(this.configuration).apiReviewOrderAddTrackUrlPost(addTrackUrlRequest, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Отменяет заказ
     * @param {CancelReviewOrderRequest} [cancelReviewOrderRequest] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public apiReviewOrderCancelReviewOrderPost(cancelReviewOrderRequest?: CancelReviewOrderRequest, options?: RawAxiosRequestConfig) {
        return ReviewOrderApiFp(this.configuration).apiReviewOrderCancelReviewOrderPost(cancelReviewOrderRequest, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Выполнение заказа
     * @param {CompleteReviewOrderRequest} [completeReviewOrderRequest] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public apiReviewOrderCompleteReviewOrderPost(completeReviewOrderRequest?: CompleteReviewOrderRequest, options?: RawAxiosRequestConfig) {
        return ReviewOrderApiFp(this.configuration).apiReviewOrderCompleteReviewOrderPost(completeReviewOrderRequest, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Создает заказ
     * @param {string} [idempotencyKey] Ключ идемпотентности
     * @param {CreateReviewOrderRequest} [createReviewOrderRequest] Запрос создания заказа
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public apiReviewOrderCreateReviewOrderPost(idempotencyKey?: string, createReviewOrderRequest?: CreateReviewOrderRequest, options?: RawAxiosRequestConfig) {
        return ReviewOrderApiFp(this.configuration).apiReviewOrderCreateReviewOrderPost(idempotencyKey, createReviewOrderRequest, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Замораживает заказ
     * @param {FreezeReviewOrderRequest} [freezeReviewOrderRequest] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public apiReviewOrderFreezeReviewOrderPost(freezeReviewOrderRequest?: FreezeReviewOrderRequest, options?: RawAxiosRequestConfig) {
        return ReviewOrderApiFp(this.configuration).apiReviewOrderFreezeReviewOrderPost(freezeReviewOrderRequest, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Поднимает заказ в очереди
     * @param {string} [idempotencyKey] Ключ идемпотентности
     * @param {MoveUpReviewOrderRequest} [moveUpReviewOrderRequest] Запрос поднятия заказа в очереди
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public apiReviewOrderMoveUpReviewOrderPost(idempotencyKey?: string, moveUpReviewOrderRequest?: MoveUpReviewOrderRequest, options?: RawAxiosRequestConfig) {
        return ReviewOrderApiFp(this.configuration).apiReviewOrderMoveUpReviewOrderPost(idempotencyKey, moveUpReviewOrderRequest, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Взятие заказа в работу
     * @param {TakeOrderInProgressRequest} [takeOrderInProgressRequest] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public apiReviewOrderTakeOrderInProgressPost(takeOrderInProgressRequest?: TakeOrderInProgressRequest, options?: RawAxiosRequestConfig) {
        return ReviewOrderApiFp(this.configuration).apiReviewOrderTakeOrderInProgressPost(takeOrderInProgressRequest, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Размораживает заказ
     * @param {UnfreezeReviewOrderRequest} [unfreezeReviewOrderRequest] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public apiReviewOrderUnfreezeReviewOrderPost(unfreezeReviewOrderRequest?: UnfreezeReviewOrderRequest, options?: RawAxiosRequestConfig) {
        return ReviewOrderApiFp(this.configuration).apiReviewOrderUnfreezeReviewOrderPost(unfreezeReviewOrderRequest, options).then((request) => request(this.axios, this.basePath));
    }
}



