<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\Faryma.Composer.Application.SharedContracts\Faryma.Composer.Application.SharedContracts.csproj" />
    <ProjectReference Include="..\Faryma.Composer.Infrastructure\Faryma.Composer.Infrastructure.csproj" />
  </ItemGroup>

</Project>
