<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <PackageReference Include="Mediator.Abstractions" Version="3.0.2" />
    <PackageReference Include="Mediator.SourceGenerator" Version="3.0.2">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Faryma.Composer.Infrastructure\Faryma.Composer.Infrastructure.csproj" />
  </ItemGroup>

</Project>
