name: ESLint

on:
  pull_request:
    branches: [ main, dev ]
    paths:
      - 'frontend/**'

jobs:
  ESLint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4.2.2

      - name: Run ESLint
        run: |
          docker run -t --rm -v "${{ github.workspace }}/frontend:/src" \
            -w /src \
            node:jod-alpine \
            sh -c "npm ci && npx eslint ."